Config                            = {
    DrawDistance = 100,
	Price = 5000,
    cars = {
        {name = "pony", label = "Pony"},
    },
    Spawngarage = {x = 130.64, y = -1717.35, z = 29.06, a = 54.00},
    Pedgarage = {x = 130.7, y = -1711.68, z = 28.28, a = 138.00}
}




Config.EnableESXIdentity = false
Config.MaxSalary = 1000
Config.EnableSalaryManagement = true
Config.MaxPrime = 15000
Config.UnemployedJob = 'unemployed'
Config.MenuColor = {0, 0, 250}

Config.Locale                     = 'fr'


Config.Shopkeeper = 416176080
Config.Locale = 'fr'

Config.Shops = {
    {coords = vector3(24.03, -1345.63, 29.5-0.98), heading = 266.0, name = 'Apu'},
    {coords = vector3(1164.94, -323.76, 68.2-0.98), heading = 100.0,  name = 'Apu'},
    {coords = vector3(372.85, 328.10, 102.56-0.98), heading = 266.0,  name = 'Apu'},
    {coords = vector3(1134.24, -983.14, 45.41-0.98), heading = 266.0,   name = 'Apu'},
    {coords = vector3(-1221.40, -908.02, 11.32-0.98), heading = 40.0,   name = 'Apu'},
    {coords = vector3(-47.39, -1758.72, 28.42-0.98), heading = 40.0,   name = 'Apu'},
    {coords = vector3(1728.62, 6416.81, 34.03-0.98), heading = 240.0,   name = 'Apu'},
    --{coords = vector3(1984.41, 3054.70, 46.21-0.98), heading = 290.0,  cops = 2, blip = true, name = 'Apu'},
    {coords = vector3(1696.92, 4923.68, 42.08-0.98), heading = 324.10,   name = 'Apu'},
    {coords = vector3(162.16, 6636.64, 31.56-0.98), heading = 135.19,   name = 'Apu'},
	{coords = vector3(-2966.37, 391.57, 15.04-0.98), heading = 100.0,   name = 'Apu'},
	{coords = vector3(-1486.64,-377.6, 40.16-0.98), heading = 140.12,   name = 'Apu'},
	{coords = vector3(-1820.52, 794.6,138.08-0.98), heading = 131.01,   name = 'Apu'}
}





Translation = {
    ['fr'] = {
        ['shopkeeper'] = 'Vendeur',
        ['robbed'] = 'Je viens de me faire braquer et je n\'ai plus d\'argent restant',
        ['cashrecieved'] = 'Vous avez recu :',
        ['currency'] = '$',
        ['scared'] = 'Peur:',
        ['no_cops'] = 'Je viens de me faire braquer et je n\'ai plus d\'argent restant',
        ['cop_msg'] = 'Une personne est entreint de Braquer Apu !',
        ['set_waypoint'] = 'Mettre un point vers le magasin',
        ['hide_box'] = 'Refuser l\'appel',
        ['robbery'] = 'Braquage en cours',
        ['walked_too_far'] = 'Vous etes partis trop loin du magasin'
    }
}

Config.CurrencyPrefix = '$' -- Ex. $ for USD - will be in front of the price
Config.CurrencySuffix = '' -- Ex. DKK for Danish Kroner - will be behind the price, remember a space in the start.

Config.ZonesP = {

    Basejumping = {
        Enable = true, -- Enable/Disable Basejumping
        Name = _U('basejumping_blip'), -- Blip Name
        DrawDistance = 15.0, -- DrawDistance lower is better! (controles how fare away you should be before the marker on the ground is drawn)
        MarkerType = 40, -- Marker Type https://forum.fivem.net/t/drawmarker-pictures-for-dev/99136
        ZoneSize = {x = 2.0, y = 2.0, z = 2.0}, -- Zone Size (How large the ring is)
        MarkerColor = {r = 0, g = 100, b = 100}, -- Marker Color RGB
        BlipSprite = 94, -- Map Marker Icon http://gtaxscripting.blogspot.com/2016/05/gta-v-blips-id-and-image.html
        BlipScale = 0.7, -- Size of Map Marker
        BlipColor = 3, -- Map Marker Color
        EnableBlips = true, -- Enable/Disable Map Markers
        Free = false, -- Controle if bike rental is free
        MenuTitle = _U('menu_title_basejumping'), -- Menu Title
        ItemType = 'weapon', -- Item Type (Is in use dont change or it will break)
        MenuActions = {
            MenuTrigger = 'basejumping_menu', -- Menu Trigger
            MenuMessage = _U('press_basejumping_menu'), -- Menu Help Text
        },
        Items = { -- Item, label, and price used for the menu
            {item = 'GADGET_PARACHUTE', label = 'Parachute', price = 350},
        },
        Pos = { -- Zone positions
            {x = 451.45, y = 5587.85, z = 781.35},
            {x = -1136.27, y = 4659.88, z = 244.15},
            {x = 1665.17, y = -28.0, z = 197.15},
            {x = -119.97, y = -977.51, z = 304.55},
            {x = -543.86, y = -2226.02, z = 122.55},
        },
        TelePos = { -- Basejump TP locations (used to launch the player for basejumping)
            {x = 446.74, y = 5587.83, z = 791.2, h = 85.5},
            {x = -1146.22, y = 4660.92, z = 243.89, h = 88.5},
            {x = 1659.73, y = -29.98, z = 208.23, h = 103.5},
            {x = -118.81, y = -979.88, z = 304.24, h = 207.5},
            {x = -539.62, y = -2228.61, z = 122.36, h = 237.5},
        }
    }
}

Config.Anims =  {
    ["S\'asseoir"] = {
            {name = "Jspske C1", anim = {"missheistdockssetup1ig_12@base", "talk_gantry_idle_base_worker2"}, func = 1},
            {name = "Jspske C2", anim = {"missheistdockssetup1ig_12@base", "talk_gantry_idle_base_worker4"}, func = 1},
            {name = "Sit 01", anim = {"amb@code_human_in_bus_passenger_idles@female@sit@base", "base"}, func = 1, a = -180.0},
            {name = "Par Terre", anim = {"anim@heists@fleeca_bank@ig_7_jetski_owner", "owner_idle"}, func = 1},
            {name = "Contre un mur", anim = "WORLD_HUMAN_LEANING"},
            {name = "Sur le Sol", anim = "WORLD_HUMAN_PICNIC"},
            {name = "Sit down", anim = {"anim@amb@office@seating@male@var_d@base@", "base"}, func = 1, a = -180.0},
            {name = "Cool", anim = {"anim@heists@heist_safehouse_intro@phone_couch@male", "phone_couch_male_idle"}, func = 1, a = -180.0},
            {name = "Sitting reflective", anim = {"missdrfriedlanderdrf_idles", "hands2face_michael"}, func = 1, a = -180.0},
            {name = "Sit down", anim = {"missdrfriedlanderdrf_idles", "hand2chin_michael"}, func = 1, a = -180.0},
            {name = "Meditation", anim = {"rcmcollect_paperleadinout@", "meditiate_idle"}, func = 1},
            {name = "Genoux sur le sol", anim = {"amb@medic@standing@kneel@base", "base"}, func = 1},
            {name = "Sit still", anim = {"missdrfriedlanderdrf_idles", "drf_idle_drf"}, func = 1},
            {name = "Chill", anim = {"missheistpaletoscoresetupleadin", "rbhs_mcs_1_leadin"}, func = 1, a = -180.0},
            {name = "Posey", anim = {"missfam2leadinoutmcs3", "onboat_leadin_pornguy_a"}, func = 1, a = -180.0},
        },
        ["Actions anim"] = {
            {name = "Bras dans le Dos", anim = {"anim@miss@low@fin@vagos@", "idle_ped06"}},
            
            {name = "Glisser", anim = {"anim@arena@celeb@flat@solo@no_props@", "slide_a_player_a"}},
            {name = "Reverence", anim = {"anim@arena@celeb@podium@no_prop@", "regal_c_1st"}},
            {name = "Pleurer sur les genoux", anim = {"mp_bank_heist_1", "f_cower_01"}, func = 1},
            {name = "Jeter votre carnet", anim = "CODE_HUMAN_MEDIC_TIME_OF_DEATH"},
            {name = "Notes", anim = "WORLD_HUMAN_CLIPBOARD"},
            {name = "Siffler", anim = {"rcmnigel1c", "hailing_whistle_waive_a"}, func = 48},
            {name = "Faire des pompes", anim = "WORLD_HUMAN_PUSH_UPS"},
            {name = "Se sentir mal", anim = {"missfam5_blackout", "pass_out"}},
            {name = "Locoooo", anim = {"anim@mp_player_intcelebrationmale@you_loco", "you_loco"}},
            {name = "Trique", anim = {"anim@mp_player_intcelebrationmale@wank", "wank"}},
            {name = "Laché moi", anim = {"anim@mp_player_intcelebrationmale@freakout", "freakout"}},
            {name = "Mendier", anim = "WORLD_HUMAN_BUM_FREEWAY"},
            {name = "Applaudir", anim = "WORLD_HUMAN_CHEERING"},
            {name = "Auplaudir lentement", anim = {"anim@mp_player_intcelebrationmale@slow_clap", "slow_clap"}},
            {name = "Appel", anim = {"cellphone@", "cellphone_call_listen_base"}, func = 49},
            {name = "Encouragement", anim = {"mini@triathlon", "male_one_handed_a"}},
            {name = "Prendre une phoo", anim = "WORLD_HUMAN_MOBILE_FILM_SHOCKING"},
            {name = "Bras tendu", anim = {"nm@hands", "flail"}, func = 1},
            {name = "Yoga", anim = {"amb@world_human_yoga@male@base", "base_a"}},
            {name = "Same", anim = {"special_ped@mime@monologue_5@monologue_5a", "10_ig_1_wa_0"}},
            {name = "Faire des abdos", anim = "WORLD_HUMAN_SIT_UPS"},
            {name = "Jeter votre carte", anim = "WORLD_HUMAN_TOURIST_MAP"},
            {name = "Acrobatie 1", anim = {"anim@arena@celeb@flat@solo@no_props@", "cap_a_player_a"}},
            {name = "Acrobatie 2", anim = {"anim@arena@celeb@flat@solo@no_props@", "flip_a_player_a"}},
            {name = "Acrobatie 3", anim = {"anim@arena@celeb@flat@solo@no_props@", "pageant_a_player_a"}},
            {name = "Radio", anim = {"random@arrests", "generic_radio_chatter"}, func = 49},
            {name = "Jardiner", anim = {"amb@world_human_gardener_plant@male@base", "base"}},
        },
    ["Gestures"] = {
            {name = "Embrasser ses doigts", anim = {"anim@mp_player_intcelebrationfemale@finger_kiss", "finger_kiss"}},
            {name = "Quoi?", anim = {"gestures@f@standing@casual", "gesture_bring_it_on"}, func = 48},
            {name = "Casser", anim = {"gestures@f@standing@casual", "gesture_bye_hard"}, func = 48},
            {name = "Wesh", anim = {"gestures@f@standing@casual", "gesture_bye_soft"}, func = 48},
            {name = "Viens voir", anim = {"gestures@f@standing@casual", "gesture_come_here_hard"}, func = 48},
            {name = "Allez ..", anim = {"gestures@f@standing@casual", "gesture_come_here_soft"}, func = 48},
            {name = "WTF?", anim = {"gestures@f@standing@casual", "gesture_damn"}, func = 48},
            {name = "Tsss", anim = {"gestures@f@standing@casual", "gesture_displeased"}, func = 48},
            {name = "Calme toi", anim = {"gestures@f@standing@casual", "gesture_easy_now"}, func = 48},
            {name = "Ici", anim = {"gestures@f@standing@casual", "gesture_hand_down"}, func = 48},
            {name = "Gauche", anim = {"gestures@f@standing@casual", "gesture_hand_left"}, func = 48},
            {name = "Droite", anim = {"gestures@f@standing@casual", "gesture_hand_right"}, func = 48},
            {name = "Oh non", anim = {"gestures@f@standing@casual", "gesture_head_no"}, func = 48},
            {name = "Hey toi", anim = {"gestures@f@standing@casual", "gesture_hello"}, func = 48},
            {name = "Lourd", anim = {"gestures@f@standing@casual", "gesture_i_will"}, func = 48},
            {name = "Moi?", anim = {"gestures@f@standing@casual", "gesture_me_hard"}, func = 48},
            {name = "Moi", anim = {"gestures@f@standing@casual", "gesture_me"}, func = 48},
            {name = "Wesh2", anim = {"gestures@f@standing@casual", "gesture_no_way"}, func = 48},
            {name = "Non non", anim = {"gestures@f@standing@casual", "gesture_nod_no_hard"}, func = 48},
            {name = "Non YZK", anim = {"gestures@f@standing@casual", "gesture_nod_no_soft"}, func = 48},
            {name = "Oui bresson", anim = {"gestures@f@standing@casual", "gesture_nod_yes_hard"}, func = 48},
            {name = "M\'ouais", anim = {"gestures@f@standing@casual", "gesture_nod_yes_soft"}, func = 48},
            {name = "C\'est ça", anim = {"gestures@f@standing@casual", "gesture_pleased"}, func = 48},
            {name = "Mon bro", anim = {"gestures@f@standing@casual", "gesture_point"}, func = 48},
            {name = "Aucune idée", anim = {"gestures@f@standing@casual", "gesture_shrug_hard"}, func = 48},
            {name = "Aucune ptn d\'idée'", anim = {"gestures@f@standing@casual", "gesture_shrug_soft"}, func = 48},
            {name = "Quoi ?!", anim = {"gestures@f@standing@casual", "gesture_what_hard"}, func = 48},
            {name = "Quoi normal ?!", anim = {"gestures@f@standing@casual", "gesture_what_soft"}, func = 48},
            {name = "Why", anim = {"gestures@f@standing@casual", "gesture_why_left"}, func = 48},
            {name = "Why 1", anim = {"gestures@f@standing@casual", "gesture_why"}, func = 48},
            {name = "Toi", anim = {"gestures@f@standing@casual", "gesture_you_hard"}, func = 48},
            {name = "Toi basique", anim = {"gestures@f@standing@casual", "gesture_you_soft"}, func = 48},
            {name = "C\'est le mien'", anim = {"gestures@f@standing@casual", "getsure_its_mine"}, func = 48},
        },
    ["Expressions"] = {
            {name = "Pouces", anim = {"anim@arena@celeb@flat@solo@no_props@", "thumbs_down_a_player_a"}, func = 48},
            {name = "Mort de rire", anim = {"anim@arena@celeb@flat@solo@no_props@", "taunt_d_player_b"}},
            {name = "Mauvais mood 1", anim = {"amb@world_human_stupor@male@base", "base"}, func = 1},
            {name = "Mauvais mood 2", anim = {"amb@world_human_stupor@male_looking_left@base", "base"}, func = 1},
            {name = "Bisoux", anim = {"mp_ped_interaction", "kisses_guy_a"}},
            {name = "Stressé", anim = {"rcmme_tracey1", "nervous_loop"}, func = 1},
            {name = "Paix", anim = {"anim@mp_player_intcelebrationmale@peace", "peace"}, func = 48},
            {name = "Clown trizo", anim = {"move_clown@p_m_two_idles@", "fidget_short_dance"}},
            {name = "Face Palm", anim = {"anim@mp_player_intcelebrationmale@face_palm", "face_palm"}},
            {name = "Patient", anim = {"special_ped@impotent_rage@base", "base"}, func = 1},
            {name = "Respect", anim = {"mp_player_int_upperbro_love", "mp_player_int_bro_love_fp"}, func = 48},
            {name = "Lunettes", anim = {"clothingspecs", "try_glasses_positive_a"}, func = 48},
            {name = "Reflexion", anim = {"misscarsteal4@aliens", "rehearsal_base_idle_director"}, func = 49},
            {name = "Regarde mon style", anim = {"clothingshirt", "try_shirt_positive_d"}, func = 48},
            {name = "Victoire", anim = {"mini@tennisexit@", "tennis_outro_win_01_female"}},
            {name = "LPF", anim = {"rcmbarry", "base"}},
            {name = "Ta dead ça chakalito!", anim = {"anim@mp_player_intcelebrationmale@thumbs_up", "thumbs_up"}},
            {name = "Migraine", anim = {"misscarsteal4@actor", "stumble"}},
            {name = "Amour d\'un bro'", anim = {"anim@mp_player_intcelebrationmale@bro_love", "bro_love"}},
            {name = "Poingnet", anim = {"anim@mp_player_intcelebrationmale@knuckle_crunch", "knuckle_crunch"}},
            {name = "Militaire", anim = {"anim@mp_player_intuppersalute", "idle_a"}, func = 49},
            {name = "GSF", anim = {"amb@code_human_in_car_mp_actions@gang_sign_b@low@ps@base", "idle_a"}, func = 48},
            {name = "Families", anim = {"amb@code_human_in_car_mp_actions@gang_sign_a@low@ps@base", "idle_a"}, func = 48},
            {name = "Vagos", anim = {"amb@code_human_in_car_mp_actions@v_sign@std@rds@base", "idle_a"}, func = 48},
            {name = "Ballas", anim = {"mp_player_int_uppergang_sign_b", "mp_player_int_gang_sign_b"}, func = 48},
            {name = "Locura", anim = {"mp_player_int_uppergang_sign_a", "mp_player_int_gang_sign_a"}, func = 48},
            {name = "Regarde moi ça!", anim = {"mp_ped_interaction", "handshake_guy_a"}},
            {name = "Regarde moi ça 2", anim = {"mp_ped_interaction", "hugs_guy_a"}},
            {name = "Bon Toutou! Aller!", anim = {"random@street_race", "grid_girl_race_start"}},
            {name = "GG!", anim = {"random@street_race", "_streetracer_accepted"}},
            {name = "BCSO", anim = {"amb@code_human_wander_idles_cop@male@static", "static"}, func = 49},
            {name = "On stop tout !", anim = {"anim@heists@ornate_bank@chat_manager", "fail"}, func = 48},
        },
    ["Poses"] = {
            {name = "Prayer", anim = {"rcmepsilonism8", "worship_base"}, func = 1},
            {name = "Auto Stop", anim = {"random@hitch_lift", "idle_f"}, func = 1},
            {name = "Allez, à genoux", anims = {
                enter = { { anim = {"random@arrests@busted", "enter"}, flag = 0 }, { anim = {"random@arrests@busted", "idle_a"}, flag = 1 } },
                exit = { { anim = {"random@arrests@busted", "exit"}, flag = 0 } }
            }
        },
            {name = "Dormir sur place", anim = {"mp_sleep", "sleep_loop"}, func = 49},
            {name = "PLS", anim = {"timetable@tracy@sleep@", "idle_c"}, func = 1},
            {name = "Rouler par terre", anim = {"missfinale_a_ig_2", "trevor_death_reaction_pt"}, func = 2},
            {name = "Blessé au sol", anim = {"combat@damage@rb_writhe", "rb_writhe_loop"}, func = 1},
            {name = "Desespéré", anim = {"rcmnigel1c", "idle_d"}, func = 1},
            {name = "Haleine", anim = {"re@construction", "out_of_breath"}},
            {name = "Faire la statue", anim = "WORLD_HUMAN_HUMAN_STATUE"},
            {name = "Faire le mec", anim = "WORLD_HUMAN_MUSCLE_FLEX"},
            {name = "Show it's muscle 2", anim = {"rcmnigel1bnmt_1b", "that_had_to_be_tyler"}},
            {name = "Extreme Meditation", anim = {"misscarsteal1leadin", "devon_idle_02"}, func = 1},
            {name = "Zombie", anim = {"special_ped@zombie@monologue_1@monologue_1c", "iamundead_2"}, func = 1},
            {name = "Guarde", anim = {"amb@world_human_stand_guard@male@base", "base"}, func = 49},
            
            {name = "Croisé relou", anim = {"anim@heists@heist_corona@single_team", "single_team_loop_boss"}, func = 1},
            {name = "JspskeC YZK", anim = {"anim@heists@heist_corona@single_team", "single_team_intro_two"}, func = 49},
            {name = "Bras Croisés", anim = {"random@street_race", "_car_b_lookout"}, func = 1},
            {name = "Holster", anim = {"reaction@intimidation@cop@unarmed", "intro"}, func = 50},
            {name = "Pataugeoire", anim = {"move_m@wading", "walk"}},
        },
    ["Festives"] = {
            {name = "Suspense", anim = {"anim@amb@nightclub@dancers@black_madonna_entourage@", "li_dance_facedj_11_v1_male^1"}, f = 1}, -- content
            {name = "Coincé", anim = {"anim@amb@nightclub@dancers@black_madonna_entourage@", "li_dance_facedj_15_v2_male^2"}, f = 1}, -- content
            {name = "Enchainé", anim = {"anim@amb@nightclub@dancers@black_madonna_entourage@", "hi_dance_facedj_09_v2_male^5"}, f = 1}, -- content
            {name = "Hey mec", anim = {"anim@amb@nightclub@dancers@club_ambientpeds@", "mi-hi_amb_club_09_v1_male^1" }, f = 1}, -- content
            {name = "Bouger 01", anim = {"anim@mp_player_intupperuncle_disco", "idle_a"}, func = 1},
            {name = "Bouger 02", anim = {"anim@mp_player_intuppersalsa_roll", "idle_a"}, func = 1},
            {name = "Bouger 03", anim = {"anim@mp_player_intupperraise_the_roof", "idle_a"}, func = 1},
            {name = "Bouger 04", anim = {"anim@mp_player_intupperoh_snap", "idle_a"}, func = 1},
            {name = "Bouger 05", anim = {"anim@mp_player_intupperheart_pumping", "idle_a"}, func = 1},
            {name = "Bouger 06", anim = {"anim@mp_player_intupperfind_the_fish", "idle_a"}, func = 1},
            {name = "Bouger 07", anim = {"anim@mp_player_intuppercats_cradle", "idle_a"}, func = 1},
            {name = "Bouger 08", anim = {"anim@mp_player_intupperbanging_tunes", "idle_a"}, func = 1},
            {name = "Bouger 09", anim = {"anim@mp_player_intupperbanging_tunes_right", "idle_a"}, func = 1},
            {name = "Bouger 10", anim = {"anim@mp_player_intupperbanging_tunes_left", "idle_a"}, func = 1},
            {name = "Play music", anim = "WORLD_HUMAN_MUSICIAN"},
            {name = "DJ", anim = {"anim@mp_player_intcelebrationmale@dj", "dj"}},
            {name = "Fausse Guitare", anim = {"anim@mp_player_intcelebrationmale@air_guitar", "air_guitar"}},
            {name = "Jazz", anim = {"anim@mp_player_intcelebrationfemale@jazz_hands", "jazz_hands"}},
            {name = "Rock'n roll", anim = {"anim@mp_player_intcelebrationmale@rock", "rock"}},
            {name = "Partying", anim = "WORLD_HUMAN_PARTYING"},
        },
    ["Insolent"] = {
            {name = "JPP", anim = {"anim@arena@celeb@flat@solo@no_props@", "giggle_a_player_a"}},
            {name = "Nettoyer le nez", anim = {"anim@mp_player_intcelebrationmale@nose_pick", "nose_pick"}},
            {name = "Bz mon doigt", anim = {"anim@mp_player_intcelebrationmale@finger", "finger"}},
            {name = "Prend mon doigt", anim = {"random@shop_gunstore", "_negative_goodbye"}},
            {name = "Nananere", anim = {"anim@mp_player_intcelebrationmale@thumb_on_ears", "thumb_on_ears"}},
            {name = "Vomir", anim = {"missfam5_blackout", "vomit"}},
            {name = "Dans ton UK", anim = {"anim@mp_player_intcelebrationmale@dock", "dock"}},
            {name = "Chuuuuute", anim = {"anim@mp_player_intcelebrationmale@shush", "shush"}},
            {name = "Mouillé", anim = {"anim@mp_player_intcelebrationmale@chicken_taunt", "chicken_taunt"}},
            {name = "Doigt célib", anims = {
            enter = {{anim = {"anim@mp_player_intselfiethe_bird", "enter"}}, {anim = {"anim@mp_player_intselfiethe_bird", "idle_a"}, flag = 49}},
            exit = {{anim = {"anim@mp_player_intselfiethe_bird", "idle_a"}}, {anim = {"anim@mp_player_intselfiethe_bird", "exit"}}},
            }
            },
            {name = "El famoso doigt", anim = {"mp_player_int_upperfinger", "mp_player_int_finger_01"}, func = 49},
            {name = "Uriner", anim = {"misscarsteal2peeing", "peeing_intro"}},
            {name = "Gratter le UK", anim = {"mp_player_int_upperarse_pick", "mp_player_int_arse_pick"}, func = 49},
            {name = "Gratter les Yekou", anim = {"mp_player_int_uppergrab_crotch", "mp_player_int_grab_crotch"}, func = 49},
            {name = "Pluie d\'argent YZK", anim = {"anim@arena@celeb@flat@solo@props@", "make_it_rain_b_player_b"}},
            {name = "Pluie d\'argent", anim = {"anim@mp_player_intcelebrationmale@raining_cash", "raining_cash"}},
            {name = "AtoûtsF", anim = {"mini@strip_club@backroom@", "stripper_b_backroom_idle_b"}},
            {name = "Coeur", anim = {"mini@hookers_spvanilla", "idle_a"}},
        },
--[[         ["Tricks (Moto)"] = {
            {name = "Moto - Jambe droite", anim = {"rcmextreme2atv", "idle_b"}, func = 1},
            {name = "Moto - Jambe gauche", anim = {"rcmextreme2atv", "idle_c"}, func = 1},
            {name = "Moto - Droite et Gauche", anim = {"rcmextreme2atv", "idle_d"}, func = 1},
            {name = "Moto - Debout", anim = {"rcmextreme2atv", "idle_e"}, func = 1},
        }, ]]
    ["Danses"] = {
        {name = "Dansant", anim = {"misschinese2_crystalmazemcs1_cs", "dance_loop_tao"}},
        {name = "Style", anim = {"missfbi3_sniping", "dance_m_default"}, func = 1},
        {name = "Banal", anim = {"rcmnigel1bnmt_1b", "dance_loop_tyler"}, func = 1},
        {name = "Special Dance 1", anim = {"timetable@tracy@ig_5@idle_a", "idle_a"}, func = 1},
        {name = "Twerk", anim = {"mini@strip_club@private_dance@part3", "priv_dance_p3"}},
        {name = "Sexy", anim = {"mp_safehouse", "lap_dance_girl"}},
        {name = "Montrer ses atoûts", anim = {"switch@trevor@mocks_lapdance", "001443_01_trvs_28_idle_stripper"}, func = 1},
        {name = "Special Dance 2", anim = {"timetable@tracy@ig_5@idle_a", "idle_b"}, func = 1},
        {name = "Special Dance 3", anim = {"timetable@tracy@ig_5@idle_b", "idle_e"}, func = 1},
        {name = "Special Dance 4", anim = {"timetable@tracy@ig_5@idle_b", "idle_d"}, func = 1},
        {name = "Pecno", anim = {"special_ped@mountain_dancer@monologue_3@monologue_3a", "mnt_dnc_buttwag"}, func = 1},
        {name = "Basique", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_hi_06_base_laz"}, func = 1},
        --{name = "Tourner", anim = {"anim@amb@night club@lazlow@hi_podium@", "danceidle_hi_11_turnaround_laz"}, func = 1},
        {name = "Dance JspskeC2", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_hi_13_crotchgrab_laz"}, func = 1},
        --{name = "Voler", anim = {"anim@amb@night club@lazlow@hi_podium@", "danceidle_hi_13_flyingv_laz"}, func = 1},
        {name = "Robot", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_mi_15_robot_laz"}, func = 1},
        {name = "Timide", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_mi_15_shimmy_laz"}, func = 1},
        --{name = "Robot Fou", anim = {"anim@amb@night club@lazlow@hi_podium@", "danceidle_hi_15_crazyrobot_laz"}, func = 1},
        {name = "Dance smack", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_hi_17_smackthat_laz"}, func = 1},
        {name = "Araignée", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_hi_17_spiderman_laz"}, func = 1},
        {name = "Hippie", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_li_13_hipswivel_laz"}, func = 1},
        --{name = "Stylé", anim = {"anim@amb@night club@lazlow@hi_podium@", "danceidle_li_15_sexygrind_laz"}, func = 1},
        --{name = "Dance JspskeC", anim = {"anim@amb@night club@lazlow@hi_podium@", "danceidle_mi_11_pointthrust_laz"}, func = 1},
        --{name = "Dance Chelou", anim = {"anim@amb@night club@lazlow@hi_podium@", "danceidle_mi_13_turnaround_laz"}, func = 1},
        {name = "Dance Wtf", anim = {"mini@strip_club@private_dance@idle", "priv_dance_idle"}, func = 1},
        
        {name = "Salsa", anim = {"anim@mp_player_intcelebrationmale@salsa_roll", "salsa_roll"}, func = 1},
        {name = "Dance 1", anim = {"anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v1_male^4"}, func = 1},
        {name = "Dance 2", anim = {"anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v2_female^1"}, func = 1},
        {name = "Dance 3", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_trans_07_mi_to_hi_laz"}, func = 1},
        {name = "Dance 4", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_trans_07_li_to_mi_laz"}, func = 1},
        {name = "Party 5", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_trans_07_hi_to_mi_laz"}, func = 1},
        {name = "Party 6", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_mi_13_enticing_laz"}, func = 1},
        {name = "Party 7", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_mi_11_simplepoint_laz"}, func = 1},
        {name = "Dance 8", anim = {"anim@amb@nightclub@djs@black_madonna@", "dance_b_idle_a_blamadon"}, func = 1},
        {name = "Dance 9", anim = {"anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "high_center"}, func = 1},
        {name = "Dance 10", anim = {"anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "med_center"}, func = 1},
        {name = "Dance 11", anim = {"anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", "high_center_up"}, func = 1},
        {name = "Disco", anim = {"anim@mp_player_intcelebrationmale@uncle_disco", "uncle_disco"}, func = 1},

        {name = "Danse casino 1", anim = {"anim@amb@casino@mini@dance@dance_solo@female@var_b@", "high_center_down"}, func = 1},
        {name = "Danse casino 2", anim = {"anim@amb@casino@mini@dance@dance_solo@female@var_b@", "high_left"}, func = 1},
        {name = "Danse casino 3", anim = {"anim@amb@casino@mini@dance@dance_solo@female@var_b@", "high_right"}, func = 1},
        {name = "Danse casino 4", anim = {"anim@amb@casino@mini@dance@dance_solo@female@var_a@", "high_left"}, func = 1},
        {name = "Danse casino 5", anim = {"anim@amb@casino@mini@dance@dance_solo@female@var_a@", "high_right"}, func = 1},
        },
        ["Armes"] = {
            {name = "Classique", anim = {}, func = function (p) SetWeaponAnimationOverride (p, GetHashKey ("Default")) end},
            {name = "Gangster", anim = {}, func = function (p) SetWeaponAnimationOverride (p, GetHashKey ("Gang1H")) ShowAboveRadarMessage ("~r~Ne fonctionne pas avec toutes les armes.") end},
            {name = "007", anim = {}, func = function (p) SetWeaponAnimationOverride (p, GetHashKey ("Hillbilly")) ShowAboveRadarMessage ("~r~Ne fonctionne pas avec toutes les armes.") end},
            {name = "JspskeC ?", anim = {}, func = function (p) SetWeaponAnimationOverride (p, GetHashKey ("FirstPersonAiming")) end},
            {name = "Execution", anim = {"oddjobs@suicide", "bystander_pointinto"}, func = 50},
            {name = "Suicide", anim = {"mp_suicide", "pistol"}, func = 2},
            {name = "Regarder l\'arme", anim = {"mp_corona@single_team", "single_team_intro_one"}},
            {name = "Arme tendu", anim = {"random@arrests", "cop_gunaimed_door_open_idle"}},
            {name = "Combat 1", anim = {"anim@deathmatch_intros@melee@2h", "intro_male_melee_2h_b"}},
            {name = "Combat 2", anim = {"anim@deathmatch_intros@melee@1h", "intro_male_melee_1h_b"}},
            {name = "Combat 3", anim = {"anim@deathmatch_intros@melee@1h", "intro_male_melee_1h_c"}},
            {name = "Combat 4", anim = {"mp_deathmatch_intros@melee@2h", "intro_male_melee_2h_d"}},
            {name = "Combat 5", anim = {"mp_deathmatch_intros@melee@2h", "intro_male_melee_2h_a_gclub"}},
            {name = "Combat 6", anim = {"mp_deathmatch_intros@melee@1h", "intro_male_melee_1h_b"}},
            {name = "Combat 1", anim = {"anim@deathmatch_intros@unarmed", "intro_male_unarmed_e"}},
            {name = "Combat 2", anim = {"anim@deathmatch_intros@unarmed", "intro_male_unarmed_d"}},
            {name = "Combat 3", anim = {"anim@deathmatch_intros@unarmed", "intro_male_unarmed_b"}},
            }
}

Config.namepedList = {
    'mp_m_freemode_01',
    'mp_f_freemode_01',
    'g_m_m_armboss_01',
    'g_m_m_armgoon_01',
    'g_m_y_armgoon_02',
    'ig_lestercrest_2',
    'g_m_m_armlieut_01',
    'g_m_m_chiboss_01',
    'g_m_m_chigoon_01',
    'g_m_m_chigoon_02',
    'ig_hao',
    'g_m_m_korboss_01',
    'g_m_y_korean_01',
    'g_m_y_korean_02',
    'g_m_y_korlieut_01',
    'a_m_m_ktown_01',
    'a_m_o_ktown_01',
    'a_m_y_ktown_01',
    'a_m_y_ktown_02',
    'g_m_y_azteca_01',
    'g_m_y_ballaeast_01',
    'g_m_y_ballaorig_01',
    'g_m_y_ballasout_01',
    'csb_ballasog',
    'csb_grove_str_dlr',
    'ig_g',
    'g_m_y_famca_01',
    'g_m_y_famdnf_01',
    'g_m_y_famfor_01',
    'ig_ramp_gang',
    's_m_y_dealer_01',
    'ig_claypain',
    'ig_clay',
    'g_m_y_lost_01',
    'g_m_y_lost_02',
    'g_m_y_lost_03',
    'a_m_m_mexcntry_01',
    'a_m_m_mexlabor_01',
    'g_m_m_mexboss_01',
    'g_m_m_mexboss_02',
    'g_m_y_mexgang_01',
    'g_m_y_mexgoon_01',
    'g_m_y_mexgoon_02',
    'g_m_y_mexgoon_03',
    'csb_ortega',
    'g_m_y_pologoon_01',
    'g_m_y_pologoon_02',
    'g_m_y_salvaboss_01',
    'g_m_y_salvagoon_01',
    'g_m_y_salvagoon_02',
    'g_m_y_salvagoon_03',
    'g_m_y_strpunk_01',
    'g_m_importexport_01',
    'g_m_y_strpunk_02',
    'a_m_m_indian_01',
    'a_m_y_indian_01',
    'a_m_m_tramp_01',
    'a_m_m_trampbeac_01',
    'a_m_o_soucent_01',
    'a_m_o_soucent_02',
    'a_m_m_salton_03',
    'a_m_o_soucent_03',
    'a_m_o_tramp_01',
    'a_m_m_acult_01',
    'a_m_o_acult_01',
    'a_m_o_acult_02',
    'a_m_y_acult_01',
    'a_m_y_acult_02',
    'ig_old_man1a',
    'ig_old_man2',
    'a_m_o_genstreet_01',
    'a_m_m_salton_02',
    'ig_ramp_hic',
    'csb_cletus',
    'ig_oneil',
    'a_m_y_salton_01',
    'a_m_m_hillbilly_01',
    'a_m_m_hillbilly_02',
    'a_m_m_afriamer_01',
    'a_m_m_farmer_01',
    'a_m_m_fatlatin_01',
    'a_m_m_genfat_01',
    'a_m_m_genfat_02',
    'a_m_m_polynesian_01',
    'a_m_y_downtown_01',
    'a_m_y_hippy_01',
    'u_m_y_hippie_01',
    'a_f_y_hippie_01',
    'a_f_m_ktown_01',
    'a_f_m_ktown_02',
    'a_f_o_ktown_01',
    'g_f_importexport_01',
    'g_f_y_ballas_01',
    'g_f_y_families_01',
    'g_f_y_lost_01',
    'g_f_y_vagos_01',
    's_m_y_clown_01',
    's_f_y_hooker_01',
    's_f_y_hooker_02',
    's_f_y_hooker_03',
    'csb_stripper_01',
    'csb_stripper_02',
    's_f_y_stripper_01',
    's_f_y_stripper_02',
    's_f_y_stripperlite',
    'a_f_y_topless_01',
    'u_m_m_streetart_01',
    'u_m_y_abner',
    's_f_y_airhostess_01',
    's_m_y_airworker',
    'u_m_m_aldinapoli',
    's_m_y_ammucity_01',
    'csb_anita',
    'csb_anton',
    'u_m_y_antonb',
    's_m_m_armoured_02',
    's_m_y_armymech_01',
    'ig_ashley',
    's_m_y_autopsy_01',
    's_m_m_autoshop_01',
    's_m_m_autoshop_02',
    'u_m_y_babyd',
    'ig_bankman',
    'u_m_m_bankman',
    's_m_y_barman_01',
    's_f_m_fembarber',
    'ig_barry',
    's_f_y_bartender_01',
    'u_m_y_baygor',
    's_f_y_baywatch_01',
    's_m_y_baywatch_01',
    'a_f_m_beach_01',
    'a_f_y_beach_01',
    'a_m_m_beach_01',
    'a_m_m_beach_02',
    'a_m_o_beach_01',
    'a_m_y_beach_01',
    'a_m_y_beach_02',
    'a_m_y_beach_03',
    'a_m_y_beachvesp_01',
    'a_m_y_beachvesp_02',
    'ig_bestmen',
    'ig_beverly',
    'a_f_m_bevhills_01',
    'a_f_m_bevhills_02',
    'a_f_y_bevhills_01',
    'a_f_y_bevhills_02',
    'a_f_y_bevhills_03',
    'a_f_y_bevhills_04',
    'a_m_m_bevhills_01',
    'a_m_m_bevhills_02',
    'a_m_y_bevhills_01',
    'a_m_y_bevhills_02',
    'u_m_m_bikehire_01',
    'u_f_y_bikerchic',
    's_m_y_blackops_01',
    's_m_y_blackops_02',
    'a_f_m_bodybuild_01',
    's_m_m_bouncer_01',
    'ig_brad',
    'a_m_y_breakdance_01',
    'csb_bride',
    'ig_bride',
    'csb_burgerdrug',
    'u_m_y_burgerdrug_01',
    's_m_y_busboy_01',
    'a_m_y_busicas_01',
    'a_f_m_business_02',
    'a_f_y_business_01',
    'a_f_y_business_02',
    'a_f_y_business_03',
    'a_f_y_business_04',
    'a_m_m_business_01',
    'a_m_y_business_01',
    'a_m_y_business_02',
    'a_m_y_business_03',
    's_m_o_busker_01',
    'csb_car3guy1',
    'ig_car3guy1',
    'csb_car3guy2',
    'ig_car3guy2',
    'ig_casey',
    'csb_chef',
    'ig_chef',
    's_m_y_chef_01',
    's_m_m_chemsec_01',
    'g_m_m_chemwork_01',
    'ig_chengsr',
    'csb_chin_goon',
    'u_m_y_chip',
    's_m_m_ciasec_01',
    'mp_m_claude_01',
    's_m_m_cntrybar_01',
    'u_f_y_comjane',
    's_m_y_construct_01',
    's_m_y_construct_02',
    'u_f_m_corpse_01',
    'u_f_y_corpse_01',
    'u_f_y_corpse_02',
    'csb_customer',
    'a_m_y_cyclist_01',
    'u_m_y_cyclist_01',
    'ig_dale',
    'csb_denise_friend',
    's_m_y_devinsec_01',
    'a_m_y_dhill_01',
    's_m_m_dockwork_01',
    's_m_y_dockwork_01',
    's_m_m_doctor_01',
    's_m_y_doorman_01',
    'a_f_m_downtown_01',
    'ig_dreyfuss',
    'ig_russiandrunk',
    's_m_y_dwservice_01',
    's_m_y_dwservice_02',
    'a_f_m_eastsa_01',
    'a_f_m_eastsa_02',
    'a_f_y_eastsa_01',
    'a_f_y_eastsa_02',
    'a_f_y_eastsa_03',
    'a_m_m_eastsa_01',
    'a_m_m_eastsa_02',
    'a_m_y_eastsa_01',
    'a_m_y_eastsa_02',
    'a_f_y_epsilon_01',
    'a_m_y_epsilon_01',
    'a_m_y_epsilon_02',
    'mp_m_exarmy_01',
    's_f_y_factory_01',
    's_m_y_factory_01',
    'a_f_m_fatbla_01',
    'a_f_m_fatcult_01',
    'a_f_m_fatwhite_01',
    'u_m_m_fibarchitect',
    'u_m_y_fibmugger_01',
    's_m_m_fiboffice_01',
    's_m_m_fiboffice_02',
    'mp_m_fibsec_01',
    'u_m_m_filmdirector',
    'u_m_o_finguru_01',
    's_m_y_fireman_01',
    'a_f_y_fitness_01',
    'a_f_y_fitness_02',
    'csb_fos_rep',
    'csb_g',
    's_m_m_gaffer_01',
    'csb_ramp_gang',
    's_m_y_garbage',
    's_m_m_gardener_01',
    'a_m_y_gay_01',
    'a_m_y_gay_02',
    'a_f_y_genhot_01',
    'a_f_o_genstreet_01',
    'a_m_y_genstreet_01',
    'a_m_y_genstreet_02',
    's_m_m_gentransport',
    'u_m_m_glenstank_01',
    'a_f_y_golfer_01',
    'a_m_m_golfer_01',
    'a_m_y_golfer_01',
    'u_m_m_griff_01',
    's_m_y_grip_01',
    'csb_groom',
    'ig_groom',
    'u_m_y_guido_01',
    'u_m_y_gunvend_01',
    's_m_m_hairdress_01',
    'csb_hao',
    'ig_hao',
    'a_m_m_hasjew_01',
    'a_m_y_hasjew_01',
    'csb_ramp_hic',
    's_m_m_highsec_01',
    's_m_m_highsec_02',
    'a_f_y_hiker_01',
    'a_m_y_hiker_01',
    'csb_ramp_hipster',
    'ig_ramp_hipster',
    'u_f_y_hotposh_01',
    'csb_hugh',
    'ig_hunter',
    's_m_y_hwaycop_01',
    'csb_imran',
    'a_f_o_indian_01',
    'a_f_y_indian_01',
    'ig_janet',
    'csb_janitor',
    's_m_m_janitor',    
    'u_m_m_jesus_01',
    'a_m_y_jetski_01',
    'ig_jewelass',  
    'u_f_y_jewelass_01',
    'u_m_m_jewelsec_01',
    'u_m_m_jewelthief', 
    'ig_jimmyboston',
    'ig_joeminuteman',
    'ig_johnnyklebitz',
    'ig_josef',
    'ig_josh',
    'a_f_y_juggalo_01',
    'a_m_y_juggalo_01',
    'u_m_y_justin',
    'ig_kerrymcintosh',
    'a_m_m_ktown_01',
    'a_m_o_ktown_01',
    'a_m_y_ktown_01',
    'a_m_y_ktown_02',
    's_m_m_lathandy_01',
    'a_m_y_latino_01',
    'ig_lazlow',
    'ig_lifeinvad_01',
    'ig_lifeinvad_02',
    's_m_m_lifeinvad_01',
    's_m_m_linecook',
    's_m_m_lsmetro_01',
    'ig_magenta',
    's_f_m_maid_01',
    'a_m_m_malibu_01',
    'u_m_y_mani',
    'ig_manuel',
    's_m_m_mariachi_01',
    'csb_ramp_marine',
    's_m_m_marine_01',
    's_m_m_marine_02',
    's_m_y_marine_01',
    's_m_y_marine_02',
    's_m_y_marine_03',
    'u_m_m_markfost',
    'mp_m_marston_01',
    'ig_maryann',
    'csb_maude',
    'ig_maude',
    'a_m_y_methhead_01',
    'csb_ramp_mex',
    'ig_ramp_mex',
    'a_m_y_mexthug_01',
    's_f_y_migrant_01',
    's_m_m_migrant_01',
    'u_m_y_militarybum',
    's_m_y_mime',
    'u_f_m_miranda',
    'u_f_y_mistress',
    'mp_f_misty_01',
    'ig_molly',
    'a_m_y_motox_01',
    'a_m_y_motox_02',
    'u_f_o_moviestar',
    's_f_y_movprem_01',
    's_m_m_movprem_01',
    's_m_m_movspace_01',
    'ig_mrs_thornhill',
    'ig_mrsphillips',
    'a_m_y_musclbeac_01',
    'a_m_y_musclbeac_02',
    'csb_mweather',
    'ig_natalia',
    'ig_nigel',
    'a_m_m_og_boss_01',
    'csb_oscar',
    'a_m_m_paparazzi_01',
    'u_m_y_paparazzi',
    'ig_paper',
    's_m_m_paramedic_01',
    'u_m_y_party_01',
    'u_m_m_partytarget',
    'ig_patricia',
    's_m_y_pestcont_01',
    's_m_m_pilot_01',
    's_m_m_pilot_02',
    's_m_y_pilot_01',
    'u_m_y_pogo_01',
    'a_m_y_polynesian_01',
    'u_f_y_poppymich',
    'csb_porndudes',
    's_m_m_postal_01',
    's_m_m_postal_02',
    'ig_priest',
    'u_f_y_princess',
    's_m_m_prisguard_01',
    's_m_y_prismuscl_01',
    's_m_y_prisoner_01',
    'u_m_y_proldriver_01',
    'a_f_m_prolhost_01',
    'a_m_m_prolhost_01',
    'u_f_o_prolhost_01',
    'csb_prologuedriver',
    'csb_prolsec',
    'ig_prolsec_02',
    'u_m_m_prolsec_01',
    'u_f_m_promourn_01',
    'u_m_m_promourn_01',
    'mp_g_m_pros_01',
    's_f_y_ranger_01',
    's_m_y_ranger_01',
    'csb_reporter',
    'u_m_m_rivalpap',
    'a_m_y_roadcyc_01',
    's_m_y_robber_01',
    'csb_roccopelosi',
    'ig_roccopelosi',
    'u_m_y_rsranger_01',
    'a_f_y_runner_01',
    'a_m_y_runner_01',
    'a_m_y_runner_02',
    'a_f_y_rurmeth_01',
    'a_m_m_rurmeth_01',
    'a_f_m_salton_01',
    'a_f_o_salton_01',
    'a_m_m_salton_01',
    'a_m_m_salton_04',
    'a_m_o_salton_01',
    'u_m_y_sbike',
    'a_f_y_scdressy_01',
    's_m_m_scientist_01',
    'csb_screen_writer',
    'ig_screen_writer',
    's_f_y_scrubs_01',
    's_m_m_security_01',
    's_f_m_shop_high',
    's_f_y_shop_low',
    's_m_y_shop_mask',
    's_f_y_shop_mid',
    'a_f_y_skater_01',
    'a_m_m_skater_01',
    'a_m_y_skater_01',
    'a_m_y_skater_02',
    'a_f_m_skidrow_01',
    'a_m_m_skidrow_01',
    's_m_m_snowcop_01',
    'a_m_m_socenlat_01',
    'a_f_m_soucent_01',
    'a_f_m_soucent_02',
    'a_f_o_soucent_01',
    'a_f_o_soucent_02',
    'a_f_y_soucent_01',
    'a_f_y_soucent_02',
    'a_f_y_soucent_03',
    'a_m_m_soucent_01',
    'a_m_m_soucent_02',
    'a_m_m_soucent_03',
    'a_m_m_soucent_04',
    'a_m_y_soucent_01',
    'a_m_y_soucent_02',
    'a_m_y_soucent_03',
    'a_m_y_soucent_04',
    'a_f_m_soucentmc_01',
    'u_m_m_spyactor',
    'u_f_y_spyactress',
    'u_m_y_staggrm_01',
    'a_m_y_stbla_01',
    'a_m_y_stbla_02',
    'a_m_m_stlat_02',
    'a_m_y_stlat_01',
    'cs_stretch',
    's_m_m_strperf_01',
    's_m_m_strpreach_01',
    's_m_m_strvend_01',
    's_m_y_strvend_01',
    'a_m_y_stwhi_01',
    'a_m_y_stwhi_02',
    'a_m_y_sunbathe_01',
    'a_m_y_surfer_01',
    's_m_y_swat_01',
    's_f_m_sweatshop_01',
    's_f_y_sweatshop_01',
    'ig_talina',
    'ig_tanisha',
    'u_m_o_taphillbilly',
    'u_m_y_tattoo_01',
    'a_f_y_tennis_01',
    'a_m_m_tennis_01',
    'ig_terry',
    'ig_tomepsilon',
    'csb_tonya',
    'ig_tonya',
    'a_f_m_tourist_01',
    'a_f_y_tourist_01',
    'a_f_y_tourist_02',
    'a_m_m_tourist_01',
    'csb_trafficwarden',
    'ig_trafficwarden',
    'a_f_m_tramp_01',
    'u_m_o_tramp_01',
    'a_f_m_trampbeac_01',
    's_m_m_trucker_01',
    'ig_tylerdix',
    's_m_m_ups_01',
    's_m_m_ups_02',
    's_m_y_uscg_01',
    's_m_y_valet_01',
    'a_m_y_vindouche_01',
    'a_f_y_vinewood_01',
    'a_f_y_vinewood_02',
    'a_f_y_vinewood_03',
    'a_f_y_vinewood_04',
    'a_m_y_vinewood_01',
    'a_m_y_vinewood_02',
    'a_m_y_vinewood_03',
    'a_m_y_vinewood_04',
    's_m_y_waiter_01',
    'u_m_m_willyfist',
    's_m_y_winclean_01',
    's_m_y_xmech_01',
    'a_f_y_yoga_01',
    'a_m_y_yoga_01',
    'ig_zimbor',
    'u_m_y_prisoner_01',
    'mp_f_boatstaff_01',
    'mp_m_boatstaff_01',
    'ig_chef2',
    'csb_chef2',
    'csb_agent',
    'ig_benny',
    's_m_y_blackops_03',
    's_m_m_ccrew_01',
    'u_m_m_doa_01',
    'u_f_m_drowned_01',
    'u_m_m_edtoh',
    'mp_f_execpa_01',
    'mp_m_execpa_01',
    's_m_m_fibsec_01',
    'u_m_o_filmnoir',
    'mp_f_helistaff_01',
    'csb_jackhowitzer',
    'csb_money',
    'ig_money',
    'csb_paige',
    'ig_paige',
    'csb_popov',
    'ig_popov',
    'csb_rashcosvki',
    'ig_rashcosvki',
    'csb_undercover',
    'mp_m_g_vagfun_01',
    'csb_vagspeak',
    'ig_vagspeak',
    'mp_f_chbar_01',
    'mp_f_cocaine_01',
    'mp_f_counterfeit_01',
    'mp_f_forgery_01',
    'mp_f_meth_01',
    'mp_f_weed_01',
    'ig_malc',
    'mp_m_cocaine_01',
    'mp_m_counterfeit_01',
    'mp_m_forgery_01',
    'mp_m_meth_01',
    'mp_m_weed_01',
    's_m_y_xmech_02_mp',
    'mp_f_cardesign_01',
    'csb_avon',
    'csb_bogdan',
    'csb_mrs_r',
    'ig_avon',
    'ig_lestercrest_2',
    'mp_f_execpa_02',
    'mp_m_avongoon',
    'mp_m_bogdangoon',
    'mp_m_securoguard_01',
    'mp_m_waremech_01',
    'mp_m_weapexp_01',
    'mp_m_weapwork_01',
    'u_m_y_corpse_01',
    'u_m_y_juggernaut_01',
    'u_m_y_smugmech_01',
    'ig_bankmann',
    'LioMessiCiv',
    'JokerSuicideSquad',
    'HarleySS',
    'therock(jeans)',
    'mp_m_niko_01',
    'mp_m_famdd_01',

}

Config = {
	DiscordToken = "ODUxNTA3OTI4OTAwNDM1OTk4.YL5Sjg.zlM6YnTBmheFMAizeWLi9yVbjM4",
	GuildId = "851507928900435998",

	-- Format: ["Role Nickname"] = "Role ID" You can get role id by doing \@RoleName
	Roles = {
        --["Offline"] = "767799456648134726" -- This would be checked by doing exports.discord_perms:IsRolePresent(user, "TestRole")
        ["Whitelist"] = "852968085463236629" -- This would be checked by doing exports.discord_perms:IsRolePresent(user, "TestRole")
	}
}




Config.Discord = "discord.gg/44m7T54zF8"


Config.Garages = {
	Centre = {	
		Pos = {x=215.800, y=-810.057, z=29.727},
		Size  = {x = 3.0, y = 3.0, z = 1.0},
		Color = {r = 204, g = 204, b = 0},
		Marker = 1,
		SpawnPoint = {
			Pos = {x=229.700, y= -800.1149, z= 29.5722},
			Color = {r=0,g=255,b=0},
			Size  = {x = 3.0, y = 3.0, z = 1.0},
			Marker = 1
		},
		DeletePoint = {
			Pos = {x=215.124, y=-791.377, z=29.646},
			Color = {r=255,g=0,b=0},
			Size  = {x = 3.0, y = 3.0, z = 1.0},
			Marker = 1
		}, 	
	},
	Paleto = {	
		Pos = {x=105.359, y=6613.586, z=31.3973},
		Size  = {x = 3.0, y = 3.0, z = 1.0},
		Color = {r = 204, g = 204, b = 0},
		Marker = 1,
		SpawnPoint = {
			Pos = {x=128.7822, y= 6622.9965, z= 30.7828},
			Color = {r=0,g=255,b=0},
			Size  = {x = 3.0, y = 3.0, z = 1.0},
			Marker = 1
		},
		DeletePoint = {
			Pos = {x=126.3572, y=6608.4150, z=30.8565},
			Color = {r=255,g=0,b=0},
			Size  = {x = 3.0, y = 3.0, z = 1.0},
			Marker = 1
		}, 	
	},

}


Clothes = Clothes or {}

Clothes.Blacklist = {
	ears_1 = {},
	watches_1 = {},
	bracelets_1 = {},
	torso_1 = {
		m = {
			[6] = true,
		},
		f = {
			[4] = true, 
		},
	},
	tshirt_1 = {
		m = {
			[23] = true, 
		},
		f = {
			[4] = true, 
		},
	},
	arms = {},
	pants_1 = { 
		m = {
			[2] = true, 
		},
		f = {
			[5] = true, 
		},
	},
	shoes_1 = {},
	helmet_1 = {
		m = {
			[4] = true, 
		},
		f = {
			[3] = true, 
		},
	},
	chain_1 = {
		m = {
			[57] = true,
		},
		f = {
			[15] = true, 
		},
	},
	bproof_1 = {
		[0] = true, 
	},
	decals_1 = {
		m = {
			[9] = true, 
		},
		f = {
			[9] = true, 
		},
	},
	bags_1 = {
		m = {
			[23] = true, 
		},
		f = {
			[23] = true, 
		},
	},
    mask_1 = {},
	glasses_1 = {},
}

Clothes.Pos = {
    {name = "clothes", pos = vector3(4.47, 6512.19, 30.88),},
    {name = "clothes", pos = vector3(1693.97, 4822.61, 41.06),},
    {name = "clothes", pos = vector3(-1101.15, 2710.81, 18.10),},
    {name = "clothes", pos = vector3(614.23, 2762.70,41.09),},
    {name = "clothes", pos = vector3(1197.1, 2710.13, 37.22),},
    {name = "clothes", pos = vector3(-3170.63, 1043.72, 19.86),},
    {name = "clothes", pos = vector3(-1450.96, -238.13, 48.81),},
    {name = "clothes", pos = vector3(-709.44, -153.78, 36.41),},
    {name = "clothes", pos = vector3(-163.19, -302.04, 38.73),},
    {name = "clothes", pos = vector3(125.78, -223.84, 53.56),},
    {name = "clothes", pos = vector3(-1193.13, -767.93, 16.32),},
    {name = "clothes", pos = vector3(-822.20, -1073.41, 10.33),},
    {name = "clothes", pos = vector3(425.56, -806.41, 28.49),},
    {name = "clothes", pos = vector3(75.36, -1392.80, 28.38)},
    {name = "mask", pos = vector3(-1337.2, -1277.13, 4.88)},
}

Config.AllTattooList = json.decode(LoadResourceFile(GetCurrentResourceName(), 'AllTattoos.json'))

Config.TattooCats = {
	{"ZONE_HEAD", "Tête", {vec(0.0, 0.7, 0.7), vec(0.7, 0.0, 0.7), vec(0.0, -0.7, 0.7), vec(-0.7, 0.0, 0.7)}, vec(0.0, 0.0, 0.5)},
	{"ZONE_LEFT_LEG", "Jambe Gauche", {vec(-0.2, 0.7, -0.7), vec(-0.7, 0.0, -0.7), vec(-0.2, -0.7, -0.7)}, vec(-0.2, 0.0, -0.6)},
	{"ZONE_LEFT_ARM", "Bras Gauche", {vec(-0.4, 0.5, 0.2), vec(-0.7, 0.0, 0.2), vec(-0.4, -0.5, 0.2)}, vec(-0.2, 0.0, 0.2)},
	{"ZONE_RIGHT_LEG", "Jambe Droite", {vec(0.2, 0.7, -0.7), vec(0.7, 0.0, -0.7), vec(0.2, -0.7, -0.7)}, vec(0.2, 0.0, -0.6)},
	{"ZONE_TORSO", "Torse/Dos", {vec(0.0, 0.7, 0.2), vec(0.0, -0.7, 0.2)}, vec(0.0, 0.0, 0.2)},
	{"ZONE_RIGHT_ARM", "Bras Droit", {vec(0.4, 0.5, 0.2), vec(0.7, 0.0, 0.2), vec(0.4, -0.5, 0.2)}, vec(0.2, 0.0, 0.2)},
}


  