Anticheat = Anticheat or {}

Anticheat.lastHealthData = { health = 0, armor = 0 }
Anticheat.ReportsDone = {}
Anticheat.CamerasEdit = {}
Anticheat.AntiCreateCam = CreateCam
Anticheat.AntiCreateCamera = CreateCamera
Anticheat.AntiDestroyCam = DestroyCam
Anticheat.AntiDestroyAllCams = DestroyAllCams

Anticheat.ESX = true 

Anticheat.AntiCarkill = false 
Anticheat.BlockWheelWeapons = true 

Anticheat.IsSpawned = false 

Anticheat.BlockTiny = true 
Anticheat.AntiGodmod = true 
Anticheat.AntiHeal = false 
Anticheat.AntiAmmoComplete = true

Anticheat.AntiCarjack = true
Anticheat.NoReloadLife = true
Anticheat.BlockNightVision = true
Anticheat.BlockThermalVision = true
Anticheat.AntiInfiniteAmmo = true
Anticheat.AntiSprintMultiplier = true
Anticheat.AntiSwimMultiplier = true

Anticheat.ExplosionProof = true
Anticheat.CollisionProof = true

Anticheat.AntiTrigger = true
Anticheat.Superjump = true

Anticheat.AntiFreecam = true

Anticheat.AntiChatMessage = true

Anticheat.AntiExplosion = true 

Anticheat.AntiSpectate = true 

Anticheat.Endpoints = {
    ["GetTextureResolution"] = true,
	["SetPedInfiniteAmmo"] = true,
	["ShootSingleBulletBetweenCoords"] = true,
	["ShootSingleBulletBetweenCoordsIgnoreEntity"] = true,
	["ShootSingleBulletBetweenCoordsIgnoreEntityNew"] = true,
	["SetSuperJumpThisFrame"] = true,
	["SetExplosiveMeleeThisFrame"] = true,
	["SetExplosiveAmmoThisFrame"] = true,
	["SetPedShootsAtCoord"] = true,
	["SetHandlingField"] = true,
	["SetHandlingInt"] = true,
	["SetHandlingFloat"] = true,
	["SetHandlingVector"] = true,
	["AddExplosion"] = true,
	["NetworkExplodeVehicle"] = true,
	["ShowHeadingIndicatorOnBlip"] = true,
	["SetBlipNameToPlayerName"] = true,
	["SetBlipCategory"] = true,
	["ApplyForceToEntity"] = true,
	["LoadResourceFile"] = true,
	["SetEntityRotation"] = true,
	["StartShapeTestRay"] = true,
	["SetPedAlertness"] = true,
	["ShootSingleBulletBetweenCoords"] = true,
	["DrawLine"] = true,
}

Anticheat.GlobalEndpoints = {
	["KeyboardInput"] = true,
	["GetKeyboardInput"] = true,
	["_Executor"] = true,
	["_Executor_Strings"] = true,
}


AnticheatConfig = AnticheatConfig or {}

AnticheatConfig.BlacklistedCaracters = {
    "'",
    "·",
    "’",
    "“",
    "”",
    "•",
    "«",
    "»",
    "•",
    "–",
    "—",
    "±",
    "×",
    "²",
    "³",
    "†",
    "‡",
    "_",
    "¹",
    "⁴",
    "⁰",
}

AnticheatConfig.BlacklistedWords = {
	'Desudo',
	'Brutan',
	'EulenCheats',
	"discord.gg/",
	"lynxmenu",
	"HamHaxia",
	"Ham Mafia",
	"www.renalua.com",
	"Fallen#0811",
	"Rena 8",
	"HamHaxia", 
	"Ham Mafia", 
	"Xanax#0134", 
	">:D Player Crash", 
	"discord.gg", 
	"34ByTe Community", 
	"lynxmenu.com", 
	"Anti-LRAC",
	"Baran#8992",
    "fdp",
    "ntm",
    "nique",
    "fils",
    "vas trouver",
    "cancer",
    "encule",
    "sucer",
    "mere",
    "mère",
    "sale",
	"iLostName#7138",
	"85.190.90.118",
	"Melon#1379",
	"hammafia.com",
	"AlphaV ~ 5391",
	"vjuton.pl",
	"Soviet Bear",
	"XARIES",
	"xaries",
	"dc.xaries.pl",
	"aries",
	"aries.pl",
	"youtube.com",
	"Aries98",
	"yo many",
	"dezet",
	"333",
	"333GANG",
    "chocolate",
	"panickey",
	"killmenu",
	"panik",
	"lynx",
	"brutan",
	"saucy",
    "negro",
    "quit",
    "uit",
    "tuck",
    "register",
    "inventory",
    "report",
    "pd",
    "juif",
    "arabe",
    "bougnoule",
    "revive",
    "pute",
    "ftg",
    "ferme",
}

AnticheatConfig.Webhook = "https://discord.com/api/webhooks/867665983044976641/QVMhskLyEioh49Xx9GUFeUVWWM1xscFUGIEVoPPrGS_FmGzxBhBM1Q0IrEc8Hk8hdbkF"

AnticheatConfig.Discord = "discord.gg/zlife"

AnticheatConfig.UseDiscord = true 
AnticheatConfig.UseSteam = true 

AnticheatConfig.BlacklistedEventsAntiESX = {
	--"esx_vehicleshop:setVehicleOwned",
	-- "esx_mafiajob:confiscatePlayerItem",
	-- "lscustoms:payGarage",
	-- "vrp_slotmachine:server:2",
	-- "Banca:deposit",
	-- "bank:deposit",
	-- "esx_jobs:caution",
	-- "give_back",
	-- "esx_fueldelivery:pay",
	-- "esx_carthief:pay",
	-- "esx_godirtyjob:pay",
	-- "esx_pizza:pay",
	-- "esx_ranger:pay",
	-- "esx_garbagejob:pay",
	-- "esx_truckerjob:pay",
	-- "redst0nia:checking",
	-- "AdminMenu:giveBank",
	-- "AdminMenu:giveCash",
	-- "esx_gopostaljob:pay",
	-- "esx_banksecurity:pay",
	-- "esx_slotmachine:sv:2",
	-- "esx:giveInventoryItem",
	-- "NB:recruterplayer",
	-- "esx_billing:sendBill",
	-- "esx_jailer:sendToJail",
	-- "esx_jail:sendToJail",
	-- "js:jailuser",
	-- "esx-qalle-jail:jailPlayer",
	-- "esx_dmvschool:pay", 
	-- "LegacyFuel:PayFuel",
	-- "OG_cuffs:cuffCheckNearest",
	-- "CheckHandcuff",
	-- "cuffServer",
	-- "cuffGranted",
	-- "police:cuffGranted",
	-- "esx_handcuffs:cuffing",
	-- "esx_policejob:handcuff",
	-- "bank:withdraw",
	-- "dmv:success",
	-- "esx_skin:responseSaveSkin",
	-- "esx_dmvschool:addLicense",
	-- "esx_mechanicjob:startCraft",
	-- "esx_drugs:startHarvestWeed",
	-- "esx_drugs:startTransformWeed",
	-- "esx_drugs:startSellWeed",
	-- "esx_drugs:startHarvestCoke",
	-- "esx_drugs:startTransformCoke",
	-- "esx_drugs:startSellCoke",
	-- "esx_drugs:startHarvestMeth",
	-- "esx_drugs:startTransformMeth",
	-- "esx_drugs:startSellMeth",
	-- "esx_drugs:startHarvestOpium",
	-- "esx_drugs:startSellOpium",
	-- "esx_drugs:startTransformOpium",
	-- "esx_blanchisseur:startWhitening",
	-- "esx_drugs:stopHarvestCoke",
	-- "esx_drugs:stopTransformCoke",
	-- "esx_drugs:stopSellCoke",
	-- "esx_drugs:stopHarvestMeth",
	-- "esx_drugs:stopTransformMeth",
	-- "esx_drugs:stopSellMeth",
	-- "esx_drugs:stopHarvestWeed",
	-- "esx_drugs:stopTransformWeed",
	-- "esx_drugs:stopSellWeed",
	-- "esx_drugs:stopHarvestOpium",
	-- "esx_drugs:stopTransformOpium",
	-- "esx_drugs:stopSellOpium",
	-- --"esx_society:openBossMenu",
	-- "esx_jobs:caution",
	-- "esx_tankerjob:pay",
	-- "esx_vehicletrunk:giveDirty",
	-- "gambling:spend",
	-- "AdminMenu:giveDirtyMoney",
	-- "esx_moneywash:deposit",
	-- "esx_moneywash:withdraw",
	-- "mission:completed",
	-- "truckerJob:success",
	-- "99kr-burglary:addMoney",
	-- "esx_jailer:unjailTime",
	-- --"esx_ambulancejob:revive",
	-- "DiscordBot:playerDied",
	-- "hentailover:xdlol",
	-- "antilynx8:anticheat",
	-- "antilynxr6:detection",
    -- --"esx:getSharedObject",
	-- --"esx_society:getOnlinePlayers",
	-- "_chat:messageEntered",
	-- "antilynx8r4a:anticheat",
	-- "antilynxr4:detect",
	-- "js:jailuser",
	-- "ynx8:anticheat",
	-- "lynx8:anticheat",
	-- "adminmenu:allowall",
	-- "h:xd",
	-- "ljail:jailplayer",
	-- "adminmenu:setsalary",
	-- "adminmenu:cashoutall",
	-- "bank:transfer",
	-- "paycheck:bonus",
	-- "paycheck:salary",
	-- "HCheat:TempDisableDetection",
	-- "esx_drugs:pickedUpCannabis",
	-- "esx_drugs:processCannabis",
	-- "esx-qalle-hunting:reward",
	-- "esx-qalle-hunting:sell",
	-- "esx_mecanojob:onNPCJobCompleted",
	-- "BsCuff:Cuff696999",
	-- "veh_SR:CheckMoneyForVeh",
	-- "esx_carthief:alertcops",
	-- "mellotrainer:adminTempBan",
	-- "mellotrainer:adminKick",
	-- "esx_society:putVehicleInGarage",
    -- "redst0nia:checking",
	-- --"gcPhone:_internalAddMessage",
	-- --"gcPhone:tchat_channel",
	-- --"esx_vehicleshop:setVehicleOwned",
	-- "esx_mafiajob:confiscatePlayerItem",
	-- "lscustoms:payGarage",
	-- "vrp_slotmachine:server:2",
	-- "Banca:deposit",
	-- "bank:deposit",
	-- "esx_jobs:caution",
	-- "give_back",
	-- "esx_fueldelivery:pay",
	-- "esx_carthief:pay",
	-- "esx_godirtyjob:pay",
	-- "esx_pizza:pay",
	-- "esx_ranger:pay",
	-- "esx_garbagejob:pay",
	-- "esx_truckerjob:pay",
	-- "AdminMenu:giveBank",
	-- "AdminMenu:giveCash",
	-- "esx_gopostaljob:pay",
	-- "esx_banksecurity:pay",
	-- "esx_slotmachine:sv:2",
	-- "esx:giveInventoryItem",
	-- "NB:recruterplayer",
	-- "esx_billing:sendBill",
	-- "esx_jailer:sendToJail",
	-- "esx_jail:sendToJail",
	-- "js:jailuser",
	-- "esx-qalle-jail:jailPlayer",
	-- "esx_dmvschool:pay",
	-- "LegacyFuel:PayFuel",
	-- "OG_cuffs:cuffCheckNearest",
	-- "CheckHandcuff",
	-- "cuffServer",
	-- "cuffGranted",
	-- "police:cuffGranted",
	-- "esx_handcuffs:cuffing",
	-- "esx_policejob:handcuff",
	-- "bank:withdraw",
	-- "dmv:success",
	-- "esx_skin:responseSaveSkin",
	-- "esx_dmvschool:addLicense",
	-- "esx_mechanicjob:startCraft",
	-- "esx_drugs:startHarvestWeed",
	-- "esx_drugs:startTransformWeed",
	-- "esx_drugs:startSellWeed",
	-- "esx_drugs:startHarvestCoke",
	-- "esx_drugs:startTransformCoke",
	-- "esx_drugs:startSellCoke",
	-- "esx_drugs:startHarvestMeth",
	-- "esx_drugs:startTransformMeth",
	-- "esx_drugs:startSellMeth",
	-- "esx_drugs:startHarvestOpium",
	-- "esx_drugs:startSellOpium",
	-- "esx_drugs:startTransformOpium",
	-- "esx_blanchisseur:startWhitening",
	-- "esx_drugs:stopHarvestCoke",
	-- "esx_drugs:stopTransformCoke",
	-- "esx_drugs:stopSellCoke",
	-- "esx_drugs:stopHarvestMeth",
	-- "esx_drugs:stopTransformMeth",
	-- "esx_drugs:stopSellMeth",
	-- "esx_drugs:stopHarvestWeed",
	-- "esx_drugs:stopTransformWeed",
	-- "esx_drugs:stopSellWeed",
	-- "esx_drugs:stopHarvestOpium",
	-- "esx_drugs:stopTransformOpium",
	-- "esx_drugs:stopSellOpium",
	-- --"esx_society:openBossMenu",
	-- "esx_jobs:caution",
	-- "esx_tankerjob:pay",
	-- "esx_vehicletrunk:giveDirty",
	-- "gambling:spend",
	-- "AdminMenu:giveDirtyMoney",
	-- "esx_moneywash:deposit",
	-- "esx_moneywash:withdraw",
	-- "mission:completed",
	-- "truckerJob:success",
	-- "99kr-burglary:addMoney",
	-- "esx_jailer:unjailTime",
	-- --"esx_ambulancejob:revive",
	-- "DiscordBot:playerDied",
	-- "hentailover:xdlol",
	-- "antilynx8:anticheat",
	-- "antilynxr6:detection",
	-- --"esx:getSharedObject",
	-- --"esx_society:getOnlinePlayers",
	-- "_chat:messageEntered",
	-- "antilynx8r4a:anticheat",
	-- "antilynxr4:detect",
	-- "js:jailuser",
	-- "ynx8:anticheat",
	-- "lynx8:anticheat",
	-- "adminmenu:allowall",
	-- "h:xd",
	-- "ljail:jailplayer",
	-- "adminmenu:setsalary",
	-- "adminmenu:cashoutall",
	-- "bank:transfer",
	-- "paycheck:bonus",
	-- "paycheck:salary",
	-- "HCheat:TempDisableDetection",
	-- "esx_drugs:pickedUpCannabis",
	-- "esx_drugs:processCannabis",
	-- "esx-qalle-hunting:reward",
	-- "esx-qalle-hunting:sell",
	-- "esx_mecanojob:onNPCJobCompleted",
	-- "BsCuff:Cuff696999",
	-- "veh_SR:CheckMoneyForVeh",
	-- "esx_carthief:alertcops",
	-- "mellotrainer:adminTempBan",
	-- "mellotrainer:adminKick",
	-- "esx_society:putVehicleInGarage",
	-- --'esx:getSharedObject',
	-- --'esx_ambulancejob:revive',
	-- --'esx_society:openBossMenu',
	-- --'esx_status:set',
	-- 'esx_policejob:handcuff',
	-- 'esx_jailer:wysylandoo',
	-- 'esx_godirtyjob:pay',
	-- 'esx_pizza:pay',
	-- 'esx_slotmachine:sv:2',
	-- 'esx_banksecurity:pay',
	-- 'esx_gopostaljob:pay',
	-- 'esx_truckerjob:pay',
	-- 'esx_carthief:pay',
	-- 'esx_garbagejob:pay',
	-- 'esx_ranger:pay',
	-- 'esx_truckersjob:payy',
	-- 'esx_blanchisseur:washMoney',
	-- 'esx_moneywash:withdraw',
	-- 'esx_blanchisseur:startWhitening',
	-- 'esx_billing:sendBill',
	-- 'esx_dmvschool:pay',
	-- 'esx_jailer:sendToJail',
	-- 'esx_jailler:sendToJail',
	-- 'esx-qalle-jail:jailPlayer',
	-- 'esx-qalle-jail:jailPlayerNew',
	-- 'esx_jailer:sendToJailCatfrajerze',
	-- 'esx_policejob:billPlayer',
	-- 'esx_skin:openRestrictedMenu',
	-- 'esx_inventoryhud:openPlayerInventory',
	-- 'bank:transfer','advancedFuel:setEssence',
	-- 'tost:zgarnijsiano',
	-- 'Sasaki_kurier:pay',
	-- 'wojtek_ubereats:napiwek',
	-- 'wojtek_ubereats:hajs',
	-- 'xk3ly-barbasz:getfukingmony',
	-- 'xk3ly-farmer:paycheck',
	-- 'tostzdrapka:wygranko',
	-- 'laundry:washcash',
	-- 'projektsantos:mandathajs',
	-- 'program-keycard:hacking',
	-- '6a7af019-2b92-4ec2-9435-8fb9bd031c26',
	-- '211ef2f8-f09c-4582-91d8-087ca2130157',
	-- 'neweden_garage:pay',
	-- '8321hiue89js',
	-- 'js:jailuser',
	-- 'wyspa_jail:jailPlayer',
	-- 'wyspa_jail:jail',
	-- --'gcPhone:sendMessage',
	-- 'ambulancier:selfRespawn',
	-- 'UnJP',
}

AnticheatConfig.BlacklistedModelss = {
    "rhino","jet","stt_prop_stunt_track_uturn","stt_prop_stunt_track_turnice","stt_prop_stunt_track_hill","prop_gold_cont_01","p_cablecar_s","stt_prop_stunt_tube_l","stt_prop_stunt_track_dwuturn","prop_fnclink_05crnr1","xs_prop_hamburgher_wl","xs_prop_plastic_bottle_wl","prop_windmill_01","p_spinning_anus_s","stt_prop_ramp_adj_flip_m","stt_prop_ramp_adj_flip_mb",
    "stt_prop_ramp_adj_flip_s","stt_prop_ramp_adj_flip_sb","stt_prop_ramp_adj_hloop","stt_prop_ramp_adj_loop","stt_prop_ramp_jump_l","stt_prop_ramp_jump_m","stt_prop_ramp_jump_s","stt_prop_ramp_jump_xl","stt_prop_ramp_jump_xs","stt_prop_ramp_jump_xxl","stt_prop_ramp_multi_loop_rb",
    "stt_prop_ramp_spiral_l","stt_prop_ramp_spiral_l_l","stt_prop_ramp_spiral_l_m","stt_prop_ramp_spiral_l_s","stt_prop_ramp_spiral_l_xxl","stt_prop_ramp_spiral_m","stt_prop_ramp_spiral_s","stt_prop_ramp_spiral_xxl","stt_prop_stunt_track_dwslope30","-145066854",
    "stt_prop_stunt_track_start","stt_prop_stunt_track_slope45","stt_prop_stunt_track_slope30","stt_prop_stunt_track_slope15","stt_prop_stunt_track_short","stt_prop_stunt_track_sh45_a","stt_prop_stunt_track_sh45","stt_prop_stunt_track_sh30",
    "stt_prop_stunt_track_sh15","stt_prop_stunt_track_otake","stt_prop_stunt_track_link","stt_prop_stunt_track_jump","stt_prop_stunt_track_hill2","stt_prop_stunt_track_hill","stt_prop_stunt_track_funnel","stt_prop_stunt_track_funlng","stt_prop_stunt_track_fork","stt_prop_stunt_track_exshort",
    "stt_prop_stunt_track_dwuturn","stt_prop_stunt_track_dwturn","stt_prop_stunt_track_dwslope45","stt_prop_stunt_track_dwslope30","stt_prop_stunt_track_dwslope15","stt_prop_stunt_track_dwshort","stt_prop_stunt_track_dwsh15","stt_prop_stunt_track_dwlink_02","stt_prop_stunt_track_dwlink",
    "stt_prop_stunt_track_cutout","stt_prop_stunt_track_bumps","stt_prop_stunt_target_small","stt_prop_stunt_target","stt_prop_stunt_soccer_sball","stt_prop_stunt_soccer_lball","stt_prop_stunt_soccer_goal","stt_prop_stunt_soccer_ball","stt_prop_stunt_ramp","stt_prop_stunt_landing_zone_01",
    "stt_prop_stunt_jump_sb","stt_prop_stunt_jump_s","stt_prop_stunt_jump_mb","stt_prop_stunt_jump_m","stt_prop_stunt_jump_loop","stt_prop_stunt_jump_lb","stt_prop_stunt_jump_l","stt_prop_stunt_jump45","stt_prop_stunt_jump30","stt_prop_stunt_jump15","stt_prop_stunt_domino",
    "prop_weed_pallet", "hei_prop_carrier_radar_1_l1", "v_res_mexball", "prop_rock_1_a", "prop_rock_1_b", "prop_rock_1_c", "prop_rock_1_d", "prop_player_gasmask", "prop_rock_1_e", "prop_rock_1_f", "prop_rock_1_g", "prop_rock_1_h", "prop_test_boulder_01", "prop_test_boulder_02", 
    "prop_test_boulder_03", "prop_test_boulder_04", "apa_mp_apa_crashed_usaf_01a", "ex_prop_exec_crashdp", "apa_mp_apa_yacht_o1_rail_a", "apa_mp_apa_yacht_o1_rail_b", "apa_mp_h_yacht_armchair_01", "apa_mp_h_yacht_armchair_03", "apa_mp_h_yacht_armchair_04", "apa_mp_h_yacht_barstool_01", 
    "apa_mp_h_yacht_bed_01", "apa_mp_h_yacht_bed_02", "apa_mp_h_yacht_coffee_table_01", "apa_mp_h_yacht_coffee_table_02", "apa_mp_h_yacht_floor_lamp_01", "apa_mp_h_yacht_side_table_01", "apa_mp_h_yacht_side_table_02", "apa_mp_h_yacht_sofa_01", "apa_mp_h_yacht_sofa_02", "apa_mp_h_yacht_stool_01", 
    "apa_mp_h_yacht_strip_chair_01", "apa_mp_h_yacht_table_lamp_01", "apa_mp_h_yacht_table_lamp_02", "apa_mp_h_yacht_table_lamp_03", "prop_flag_columbia", "apa_mp_apa_yacht_o2_rail_a", "apa_mp_apa_yacht_o2_rail_b", "apa_mp_apa_yacht_o3_rail_a", "apa_mp_apa_yacht_o3_rail_b", "apa_mp_apa_yacht_option1",
    "proc_searock_01", "apa_mp_h_yacht_", "apa_mp_apa_yacht_option1_cola", "apa_mp_apa_yacht_option2", "apa_mp_apa_yacht_option2_cola", "apa_mp_apa_yacht_option2_colb", "apa_mp_apa_yacht_option3", "apa_mp_apa_yacht_option3_cola", "apa_mp_apa_yacht_option3_colb", "apa_mp_apa_yacht_option3_colc", 
    "apa_mp_apa_yacht_option3_cold", "apa_mp_apa_yacht_option3_cole", "apa_mp_apa_yacht_jacuzzi_cam", "apa_mp_apa_yacht_jacuzzi_ripple003", "apa_mp_apa_yacht_jacuzzi_ripple1", "apa_mp_apa_yacht_jacuzzi_ripple2", "apa_mp_apa_yacht_radar_01a", "apa_mp_apa_yacht_win", "prop_crashed_heli", "apa_mp_apa_yacht_door", 
    "prop_shamal_crash", "xm_prop_x17_shamal_crash", "apa_mp_apa_yacht_door2", "apa_mp_apa_yacht", "prop_flagpole_2b", "prop_flagpole_2c", "prop_flag_canada", "apa_prop_yacht_float_1a", "apa_prop_yacht_float_1b", "apa_prop_yacht_glass_01", "apa_prop_yacht_glass_02", 
    "apa_prop_yacht_glass_03", "apa_prop_yacht_glass_04", "apa_prop_yacht_glass_05", "apa_prop_yacht_glass_06", "apa_prop_yacht_glass_07", "apa_prop_yacht_glass_08", "apa_prop_yacht_glass_09", "apa_prop_yacht_glass_10", "prop_flag_canada_s", "prop_flag_eu", "prop_flag_eu_s", 
    "prop_target_blue_arrow", "prop_target_orange_arrow", "prop_target_purp_arrow", "prop_target_red_arrow", "apa_prop_flag_argentina", "apa_prop_flag_australia", "apa_prop_flag_austria", "apa_prop_flag_belgium", "apa_prop_flag_brazil", "apa_prop_flag_canadat_yt", "apa_prop_flag_china", 
    "apa_prop_flag_columbia", "apa_prop_flag_croatia", "apa_prop_flag_czechrep", "apa_prop_flag_denmark", "apa_prop_flag_england", "apa_prop_flag_eu_yt", "apa_prop_flag_finland", "apa_prop_flag_france", "apa_prop_flag_german_yt", "apa_prop_flag_hungary", "apa_prop_flag_ireland", 
    "apa_prop_flag_israel", "apa_prop_flag_italy", "apa_prop_flag_jamaica", "apa_prop_flag_japan_yt", "apa_prop_flag_canada_yt", "apa_prop_flag_lstein", "apa_prop_flag_malta", "apa_prop_flag_mexico_yt", "apa_prop_flag_netherlands", "apa_prop_flag_newzealand", "apa_prop_flag_nigeria", 
    "apa_prop_flag_norway", "apa_prop_flag_palestine", "apa_prop_flag_poland", "apa_prop_flag_portugal", "apa_prop_flag_puertorico", "apa_prop_flag_russia_yt", "apa_prop_flag_scotland_yt", "apa_prop_flag_script", "apa_prop_flag_slovakia", "apa_prop_flag_slovenia", "apa_prop_flag_southafrica", 
    "apa_prop_flag_southkorea", "apa_prop_flag_spain", "apa_prop_flag_sweden", "apa_prop_flag_switzerland", "apa_prop_flag_turkey", "apa_prop_flag_uk_yt", "apa_prop_flag_us_yt", "apa_prop_flag_wales", "prop_flag_uk", "prop_flag_uk_s", "prop_flag_us", "prop_flag_usboat", "prop_flag_us_r", 
    "prop_flag_us_s", "prop_flag_france", "prop_flag_france_s", "prop_flag_german", "prop_flag_german_s", "prop_flag_ireland", "prop_flag_ireland_s", "prop_flag_japan", "prop_flag_japan_s", "prop_flag_ls", "prop_flag_lsfd", "prop_flag_lsfd_s", "prop_flag_lsservices", "prop_flag_lsservices_s", 
    "prop_flag_ls_s", "prop_flag_mexico", "prop_flag_mexico_s", "prop_flag_russia", "prop_flag_russia_s", "prop_flag_s", "prop_flag_sa", "prop_flag_sapd", "prop_flag_sapd_s", "prop_flag_sa_s", "prop_flag_scotland", "prop_flag_scotland_s", "prop_flag_sheriff", "prop_flag_sheriff_s", 
    "prop_flag_uk", "prop_flag_uk_s", "prop_flag_us", "prop_flag_usboat", "prop_flag_us_r", "prop_flag_us_s", "prop_flamingo", "prop_swiss_ball_01", "prop_air_bigradar_l1", "prop_air_bigradar_l2", "prop_air_bigradar_slod", "p_fib_rubble_s", "prop_money_bag_01", "p_cs_mp_jet_01_s", 
    "prop_poly_bag_money", "prop_air_radar_01", "hei_prop_carrier_radar_1", "prop_air_bigradar", "prop_carrier_radar_1_l1", "prop_asteroid_01", "prop_xmas_ext", "p_oil_pjack_01_amo", "p_oil_pjack_01_s", "p_oil_pjack_02_amo", "p_oil_pjack_03_amo", "p_oil_pjack_02_s", "p_oil_pjack_03_s", 
    "prop_aircon_l_03", "prop_med_jet_01", "p_med_jet_01_s", "hei_prop_carrier_jet", "bkr_prop_biker_bblock_huge_01", "bkr_prop_biker_bblock_huge_02", "bkr_prop_biker_bblock_huge_04", "bkr_prop_biker_bblock_huge_05", "hei_prop_heist_emp", "prop_weed_01", "prop_air_bigradar", 
    "prop_juicestand", "prop_lev_des_barge_02", "hei_prop_carrier_defense_01", "prop_aircon_m_04", "prop_mp_ramp_03", "stt_prop_stunt_track_dwuturn", "ch3_12_animplane1_lod", "ch3_12_animplane2_lod", "hei_prop_hei_pic_pb_plane", "light_plane_rig", "prop_cs_plane_int_01", "prop_dummy_plane", 
    "prop_mk_plane", "v_44_planeticket", "prop_planer_01", "ch3_03_cliffrocks03b_lod", "ch3_04_rock_lod_02", "csx_coastsmalrock_01_", "csx_coastsmalrock_02_", "csx_coastsmalrock_03_", "csx_coastsmalrock_04_", "mp_player_introck", "Heist_Yacht", "csx_coastsmalrock_05_", "mp_player_int_rock", 
    "mp_player_introck", "prop_flagpole_1a", "prop_flagpole_2a", "prop_flagpole_3a", "prop_a4_pile_01", "cs2_10_sea_rocks_lod", "cs2_11_sea_marina_xr_rocks_03_lod", "prop_gold_cont_01", "prop_hydro_platform", "ch3_04_viewplatform_slod", "ch2_03c_rnchstones_lod", "proc_mntn_stone01", 
    "prop_beachflag_le", "proc_mntn_stone02", "cs2_10_sea_shipwreck_lod", "des_shipsink_02", "prop_dock_shippad", "des_shipsink_03", "des_shipsink_04", "prop_mk_flag", "prop_mk_flag_2", "proc_mntn_stone03", "FreeModeMale01", "rsn_os_specialfloatymetal_n", "rsn_os_specialfloatymetal", 
    "cs1_09_sea_ufo", "rsn_os_specialfloaty2_light2", "rsn_os_specialfloaty2_light", "rsn_os_specialfloaty2", "rsn_os_specialfloatymetal_n", "rsn_os_specialfloatymetal", "P_Spinning_Anus_S_Main", "P_Spinning_Anus_S_Root", "cs3_08b_rsn_db_aliencover_0001cs3_08b_rsn_db_aliencover_0001_a", 
    "sc1_04_rnmo_paintoverlaysc1_04_rnmo_paintoverlay_a", "rnbj_wallsigns_0001", "proc_sml_stones01", "proc_sml_stones02", "maverick", "Miljet", "proc_sml_stones03", "proc_stones_01", "proc_stones_02", "proc_stones_03", "proc_stones_04", "proc_stones_05", "proc_stones_06", "prop_coral_stone_03", 
    "prop_coral_stone_04", "prop_gravestones_01a", "prop_gravestones_02a", "prop_gravestones_03a", "prop_gravestones_04a", "prop_gravestones_05a", "prop_gravestones_06a", "prop_gravestones_07a", "prop_gravestones_08a", "prop_gravestones_09a", "prop_gravestones_10a", "prop_prlg_gravestone_05a_l1", 
    "prop_prlg_gravestone_06a", "prop_ld_toilet_01", "test_prop_gravestones_04a", "test_prop_gravestones_05a", "test_prop_gravestones_07a", "test_prop_gravestones_08a", "test_prop_gravestones_09a", "prop_prlg_gravestone_01a", "prop_prlg_gravestone_02a", "prop_prlg_gravestone_03a", "prop_prlg_gravestone_04a", 
    "prop_stoneshroom1", "prop_stoneshroom2", "v_res_fa_stones01", "test_prop_gravestones_01a", "test_prop_gravestones_02a", "prop_prlg_gravestone_05a", "FreemodeFemale01", "p_cablecar_s", "stt_prop_stunt_tube_l", "stt_prop_stunt_track_dwuturn", "p_spinning_anus_s", "prop_windmill_01", 
    "hei_prop_heist_tug", "prop_air_bigradar", "p_oil_slick_01", "prop_dummy_01", "hei_prop_heist_emp", "p_tram_cash_s", "hw1_blimp_ce2", "prop_fire_exting_1a", "prop_fire_exting_1b", "prop_fire_exting_2a", "prop_fire_exting_3a", "hw1_blimp_ce2_lod", "hw1_blimp_ce_lod", "hw1_blimp_cpr003", 
    "hw1_blimp_cpr_null", "hw1_blimp_cpr_null2", "prop_lev_des_barage_02", "hei_prop_carrier_defense_01", "prop_juicestand", "S_M_M_MovAlien_01", "s_m_m_movalien_01", "s_m_m_movallien_01", "u_m_y_babyd", "CS_Orleans", "A_M_Y_ACult_01", "S_M_M_MovSpace_01", "U_M_Y_Zombie_01", 
    "s_m_y_blackops_01", "a_f_y_topless_01", "a_c_boar", "a_c_cat_01", "a_c_chickenhawk", "a_c_chimp", "s_f_y_hooker_03", "a_c_chop", "a_c_cormorant", "a_c_cow", "a_c_coyote", "v_ilev_found_cranebucket", "p_cs_sub_hook_01_s", "a_c_crow", "a_c_dolphin", "a_c_fish", "hei_prop_heist_hook_01", 
    "prop_rope_hook_01", "prop_sub_crane_hook", "s_f_y_hooker_01", "prop_vehicle_hook", "prop_v_hook_s", "prop_dock_crane_02_hook", "prop_winch_hook_long", "a_c_hen", "a_c_humpback", "a_c_husky", "a_c_killerwhale", "a_c_mtlion", "a_c_pigeon", "a_c_poodle", "prop_coathook_01", "prop_cs_sub_hook_01", 
    "a_c_pug", "a_c_rabbit_01", "a_c_rat", "a_c_retriever", "a_c_rhesus", "a_c_rottweiler", "a_c_sharkhammer", "a_c_sharktiger", "a_c_shepherd", "a_c_stingray", "a_c_westy", "CS_Orleans", "prop_windmill_01", "prop_Ld_ferris_wheel", "p_tram_crash_s", "p_oil_slick_01", "p_ld_soc_ball_01", 
    "p_parachute1_s", "p_cablecar_s", "prop_beach_fire", "prop_lev_des_barge_02", "prop_lev_des_barge_01", "prop_sculpt_fix", "prop_flagpole_2b", "prop_flagpole_2c", "prop_winch_hook_short", "prop_flag_canada", "prop_flag_canada_s", "prop_flag_eu", "prop_flag_eu_s", "prop_flag_france", 
    "prop_flag_france_s", "prop_flag_german", "prop_ld_hook", "prop_flag_german_s", "prop_flag_ireland", "prop_flag_ireland_s", "prop_flag_japan", "prop_flag_japan_s", "prop_flag_ls", "prop_flag_lsfd", "prop_flag_lsfd_s", "prop_cable_hook_01", "prop_flag_lsservices", "prop_flag_lsservices_s", 
    "prop_flag_ls_s", "prop_flag_mexico", "prop_flag_mexico_s", "csx_coastboulder_00", "des_tankercrash_01", "des_tankerexplosion_01", "des_tankerexplosion_02", "des_trailerparka_02", "des_trailerparkb_02", "des_trailerparkc_02", "des_trailerparkd_02", "des_traincrash_root2", "des_traincrash_root3", 
    "des_traincrash_root4", "des_traincrash_root5", "des_finale_vault_end", "des_finale_vault_root001", "des_finale_vault_root002", "des_finale_vault_root003", "des_finale_vault_root004", "des_finale_vault_start", "des_vaultdoor001_root001", "des_vaultdoor001_root002", "des_vaultdoor001_root003", 
    "des_vaultdoor001_root004", "des_vaultdoor001_root005", "des_vaultdoor001_root006", "des_vaultdoor001_skin001", "des_vaultdoor001_start", "des_traincrash_root6", "prop_ld_vault_door", "prop_vault_door_scene", "prop_vault_door_scene", "prop_vault_shutter", "p_fin_vaultdoor_s", 
    "prop_gold_vault_fence_l", "prop_gold_vault_fence_r", "prop_gold_vault_gate_01", "des_traincrash_root7", "prop_flag_russia", "prop_flag_russia_s", "prop_flag_s", "ch2_03c_props_rrlwindmill_lod", "prop_flag_sa", "prop_flag_sapd", "prop_flag_sapd_s", "prop_flag_sa_s", "prop_flag_scotland", 
    "prop_flag_scotland_s", "prop_flag_sheriff", "prop_flag_sheriff_s", "prop_flag_uk", "prop_yacht_lounger", "prop_yacht_seat_01", "prop_yacht_seat_02", "prop_yacht_seat_03", "marina_xr_rocks_02", "marina_xr_rocks_03", "prop_test_rocks01", "prop_test_rocks02", "prop_test_rocks03", 
    "prop_test_rocks04", "marina_xr_rocks_04", "marina_xr_rocks_05", "marina_xr_rocks_06", "prop_yacht_table_01", "csx_searocks_02", "csx_searocks_03", "csx_searocks_04", "csx_searocks_05", "csx_searocks_06", "p_yacht_chair_01_s", "p_yacht_sofa_01_s", "prop_yacht_table_02", "csx_coastboulder_00", 
    "csx_coastboulder_01", "csx_coastboulder_02", "csx_coastboulder_03", "csx_coastboulder_04", "csx_coastboulder_05", "csx_coastboulder_06", "csx_coastboulder_07", "csx_coastrok1", "csx_coastrok2", "csx_coastrok3", "csx_coastrok4", "csx_coastsmalrock_01", "csx_coastsmalrock_02", 
    "csx_coastsmalrock_03", "csx_coastsmalrock_04", "csx_coastsmalrock_05", "prop_yacht_table_03", "prop_flag_uk_s", "prop_flag_us", "prop_flag_usboat", "prop_flag_us_r", "prop_flag_us_s", "p_gasmask_s", "prop_flamingo", "prop_doghouse_01", "prop_gas_pump_1a", "prop_gas_pump_1c", "prop_gas_pump_1b", "prop_gas_pump_1d", 
    "prop_gas_tank_04a", "prop_gas_tank_02a", "prop_gas_tank_02b", "prop_gas_tank_01a", "prop_tanktrailer_01a", "prop_rail_tankcar", "prop_air_watertank3", "prop_storagetank_07a", "prop_ld_farm_couch01", "prop_crashed_heli", "prop_rock_4_d", "prop_rock_4_c", "prop_rock_1_f", "prop_rock_3_h", "prop_rock_3_a", "prop_rock_3_i", 
    "prop_rock_2_d", "prop_test_rocks03", "prop_test_rocks02", "apa_mp_h_acc_rugwoolm_03", "prop_gas_pump_old3", "prop_ballistic_shield", "prop_container_05a", "prop_fnclink_03a",
    
    "prop_container_03b", "lts_prop_lts_ramp_01", "lts_prop_lts_ramp_02", "lts_prop_lts_ramp_03", "prop_jetski_ramp_01", "stt_prop_ramp_adj_hloop", "stt_prop_ramp_jump_xxl", "cs_x_rubweea", "cs_x_weesmlb", "cs_x_rubweec", "cs_x_rubweed", "cs_x_rubweee",
    "hei_prop_carrier_radar_1", "hei_prop_gold_trolly_empty", "hei_prop_heist_tug", "lts_prop_lts_offroad_tyres01", "p_cs_mp_jet_01_s", "p_gate_prison_01_s", "stt_prop_stunt_jump30", "stt_prop_stunt_jump45", "stt_prop_stunt_track_dwslope15", "stt_prop_stunt_track_dwslope30", 
    "stt_prop_stunt_track_funlng", "stt_prop_stunt_track_jump", "stt_prop_stunt_track_st_01", "stt_prop_stunt_track_start", "stt_prop_stunt_tube_l", "stt_prop_stunt_tube_m",

    "hei_prop_carrier_defense_01", "hei_prop_heist_magnet", "hei_prop_heist_tug", "ind_prop_dlc_roller_car", "lts_prop_lts_elecbox_24b", "lts_prop_lts_ramp_01", "lts_prop_lts_ramp_02", "lts_prop_lts_ramp_03", "lts_prop_lts_elecbox_24", "xs_prop_plastic_bottle_wl",
    "prop_flag_canada", "prop_flag_eu", "prop_flag_france", "prop_flag_german", "prop_flag_ireland", "prop_flag_japan", "prop_flag_ls", "prop_flag_lsfd", "prop_flag_lsservices", "prop_flag_mexico", "prop_flag_russia", "prop_flag_sa", "prop_flag_sapd", "prop_flag_scotland", "prop_flag_sheriff", "prop_flag_uk", "prop_flag_us", "prop_golfflag",
    "prop_dummy_plane", "hei_prop_heist_apecrate", "prop_tool_broom", "prop_surf_board_04", "prop_bush_lrg_01c_cr", "xm_prop_x17_sub", "prop_ld_farm_couch02", 
    "hei_prop_carrier_cargo_02a", "p_cablecar_s", "p_ferris_car_01", "prop_cj_big_boat", "prop_rock_4_big2", "prop_steps_big_01", "v_ilev_lest_bigscreen", "prop_carcreeper", "apa_mp_h_bed_double_09", "apa_mp_h_bed_wide_05", "sanchez", "cargobob", "prop_cattlecrush", "prop_cs_documents_01",
    "stt_prop_stunt_track_dwslope30", 

    "a_c_cat_01", "prop_mp_spike_01", "prop_tyre_spike_01", "prop_container_ld2", "lts_prop_lts_ramp_03", "prop_jetski_ramp_01", "prop_mp_ramp_03_tu", "prop_skate_flatramp_cr", "stt_prop_ramp_adj_loop", "stt_prop_ramp_multi_loop_rb", "stt_prop_ramp_spiral_l", "stt_prop_ramp_spiral_l_m", "prop_const_fence03b_cr", "prop_const_fence02b", "prop_const_fence03a_cr", "prop_fnc_farm_01e", "prop_fnccorgm_02c", "ch3_01_dino", "p_pallet_02a_s", "prop_conc_blocks01a", "hei_prop_cash_crate_half_full", "prop_consign_01a", "prop_byard_net02", "prop_mb_cargo_04b", "prop_mb_crate_01a_set", "prop_pipe_stack_01", "prop_roadcone01c", "prop_rub_cage01b", "prop_sign_road_01a", "prop_sign_road_03m", "prop_traffic_rail_2", "prop_traffic_rail_1a", "prop_traffic_03a", "prop_traffic_01d", "prop_skid_trolley_1", "hei_prop_yah_seat_03", "hei_prop_yah_table_03", "lts_prop_lts_elecbox_24", "lts_prop_lts_elecbox_24b", "p_airdancer_01_s", "p_amb_brolly_01", "p_amb_brolly_01_s", "p_dumpster_t", "p_ld_coffee_vend_01", "p_patio_lounger1_s", "p_yacht_sofa_01_s", "prop_air_bagloader2_cr", "prop_air_bigradar", "prop_air_blastfence_01", "prop_air_stair_01", "prop_air_sechut_01", "prop_airport_sale_sign",
    "prop_container_05a", "stt_prop_stunt_bowling_ball", "prop_container_ld2", "prop_container_05a",
}

AnticheatConfig.WhitelistPedModelss = {
    'S_M_M_TRUCKER_01',
    'MP_M_WAREMECH_01',
    'g_m_y_lost_01',
	'g_m_y_lost_02',
	'g_m_y_lost_03',
	'a_f_m_bevhills_01',
	'a_f_m_fatbla_01',
	'a_f_m_fatwhite_01',
	'a_f_m_soucentmc_01',
	'a_f_m_soucent_01',
	'a_f_m_soucent_02',
	'a_f_m_tourist_01',
	'a_f_m_prolhost_01',
	'a_f_m_skidrow_01',
	'a_f_o_indian_01',
	'a_f_y_bevhills_01',
	'a_f_y_bevhills_02',
	'a_f_y_bevhills_03',
	'a_f_y_bevhills_04',
	'a_f_y_business_01',
	'a_f_y_business_02',
	'a_f_y_business_03',
	'a_f_y_business_04',
	'a_f_y_eastsa_01',
	'a_f_y_eastsa_02',
	'a_f_y_eastsa_03',
	'a_f_y_epsilon_01',
	'a_f_y_fitness_01',
	'a_f_y_fitness_02',
	'a_f_y_genhot_01',
	'a_f_y_golfer_01',
	'a_f_y_hiker_01',
	'a_f_y_hippie_01',
	'a_f_y_hipster_01',
	'a_f_y_hipster_02',
	'a_f_y_hipster_03',
	'a_f_y_hipster_04',
	'a_f_y_indian_01',
	'a_f_y_juggalo_01',
	'a_f_y_runner_01',
	'a_f_y_rurmeth_01',
	'a_f_y_scdressy_01',
	'a_f_y_skater_01',
	'a_f_y_soucent_01',
	'a_f_y_soucent_02',
	'a_f_y_soucent_03',
	'a_f_y_tennis_01',
	'a_f_y_tourist_01',
	'a_f_y_tourist_02',
	'a_f_y_vinewood_01',
	'a_f_y_vinewood_02',
	'a_f_y_vinewood_03',
	'a_f_y_vinewood_04',
	'a_f_y_yoga_01',
	'a_m_m_afriamer_01',
	'a_m_m_beach_01',
	'a_m_m_bevhills_01',
	'a_m_m_bevhills_02',
	'a_m_m_business_01',
	'a_m_m_eastsa_01',
	'a_m_m_eastsa_02',
	'a_m_m_farmer_01',
	'a_m_m_fatlatin_01',
	'a_m_m_genfat_01',
	'a_m_m_genfat_02',
	'a_m_m_golfer_01',
	'a_m_m_hasjew_01',
	'a_m_m_hillbilly_01',
	'a_m_m_hillbilly_02',
	'a_m_m_indian_01',
	'a_m_m_ktown_01',
	'a_m_m_malibu_01',
	'a_m_m_mexcntry_01',
	'a_m_m_mexlabor_01',
	'a_m_m_og_boss_01',
	'a_m_m_paparazzi_01',
	'a_m_m_polynesian_01',
	'a_m_m_prolhost_01',
	'a_m_m_rurmeth_01',
	'a_m_m_salton_01',
	'a_m_m_salton_02',
	'a_m_m_salton_03',
	'a_m_m_salton_03',
	'a_m_m_skater_01',
	'a_m_m_skidrow_01',
	'a_m_m_socenlat_01',
	'a_m_m_soucent_01',
	'a_m_m_soucent_02',
	'a_m_m_soucent_03',
	'a_m_m_soucent_04',
	'a_m_m_stlat_02',
	'a_m_m_tennis_01',
	'a_m_m_tourist_01',
	'a_m_m_trampbeac_01',
	'a_m_m_tramp_01',
	'a_m_m_tramp_01',
	'a_m_o_acult_02',
	'a_m_o_beach_01',
	'a_m_o_genstreet_01',
	'a_m_o_ktown_01',
	'a_m_o_salton_01',
	'a_m_o_soucent_01',
	'a_m_o_soucent_02',
	'a_m_o_soucent_03',
	'a_m_o_tramp_01',
	'a_m_y_beachvesp_01',
	'a_m_y_beachvesp_02',
	'a_m_y_beach_01',
	'a_m_y_beach_02',
	'a_m_y_beach_03',
	'a_m_y_bevhills_01',
	'a_m_y_bevhills_02',
	'a_m_y_breakdance_01',
	'a_m_y_busicas_01',
	'a_m_y_business_01',
	'a_m_y_business_02',
	'a_m_y_business_03',
	'a_m_y_cyclist_01',
	'a_m_y_dhill_01',
	'a_m_y_downtown_01',
	'a_m_y_eastsa_01',
	'a_m_y_eastsa_02',
	'a_m_y_epsilon_01',
	'a_m_y_epsilon_02',
	'a_m_y_gay_01',
	'a_m_y_gay_02',
	'a_m_y_genstreet_01',
	'a_m_y_genstreet_02',
	'a_m_y_golfer_01',
	'a_m_y_hasjew_01',
	'a_m_y_hiker_01',
	'a_m_y_hippy_01',
	'a_m_y_hipster_01',
	'a_m_y_hipster_02',
	'a_m_y_hipster_03',
	'a_m_y_indian_01',
	'a_m_y_jetski_01',
	'a_m_y_juggalo_01',
	'a_m_y_ktown_01',
	'a_m_y_ktown_02',
	'a_m_y_latino_01',
	'a_m_y_methhead_01',
	'a_m_y_mexthug_01',
	'a_m_y_motox_01',
	'a_m_y_motox_02',
	'a_m_y_musclbeac_02',
	'a_m_y_polynesian_01',
	'a_m_y_roadcyc_01',
	'a_m_y_runner_01',
	'a_m_y_runner_02',
	'a_m_y_salton_01',
	'a_m_y_skater_01',
	'a_m_y_skater_02',
	'a_m_y_soucent_01',
	'a_m_y_soucent_02',
	'a_m_y_soucent_03',
	'a_m_y_soucent_04',
	'a_m_y_stbla_01',
	'a_m_y_stbla_02',
	'a_m_y_stlat_01',
	'a_m_y_stwhi_01',
	'a_m_y_stwhi_02',
	'a_m_y_sunbathe_01',
	'a_m_y_vindouche_01',
	'a_m_y_vinewood_01',
	'a_m_y_vinewood_02',
	'a_m_y_vinewood_03',
	'a_m_y_vinewood_04',
	'a_m_y_yoga_01',
	'csb_abigail',
	'csb_anita',
	'csb_anton',
	'csb_ballasog',
	'csb_car3guy1',
	'csb_car3guy2',
	'csb_chin_goon',
	'csb_cletus',
	'csb_customer',
	'csb_denise_friend',
	'csb_fos_rep',
	'csb_groom',
	'csb_grove_str_dlr',
	'csb_g',
	'csb_hao',
	'csb_hugh',
	'csb_imran',
	'csb_janitor',
	'csb_ortega',
	'csb_oscar',
	'csb_porndudes',
	'csb_prologuedriver',
	'csb_ramp_gang',
	'csb_ramp_hic',
	'csb_ramp_hipster',
	'csb_ramp_mex',
	'csb_reporter',
	'csb_roccopelosi',
	'csb_screen_writer',
	'csb_stripper_01',
	'csb_tonya',
	'g_f_y_ballas_01',
	'g_f_y_families_01',
	'g_f_y_families_01',
	'g_f_y_vagos_01',
	'g_m_m_armboss_01',
	'g_m_m_armgoon_01',
	'g_m_m_armlieut_01',
	'g_m_m_chiboss_01',
	'g_m_m_chicold_01',
	'g_m_m_chigoon_01',
	'g_m_m_chigoon_02',
	'g_m_m_korboss_01',
	'g_m_m_mexboss_01',
	'g_m_m_mexboss_02',
	'g_m_y_armgoon_02',
	'g_m_y_azteca_01',
	'g_m_y_ballaeast_01',
	'g_m_y_ballaorig_01',
	'g_m_y_ballasout_01',
	'g_m_y_famca_01',
	'g_m_y_famdnf_01',
	'g_m_y_famfor_01',
	'g_m_y_korean_01',
	'g_m_y_korean_02',
	'g_m_y_korlieut_01',
	'g_m_y_mexgang_01',
	'g_m_y_mexgoon_01',
	'g_m_y_mexgoon_02',
	'g_m_y_mexgoon_03',
	'g_m_y_pologoon_01',
	'g_m_y_pologoon_02',
	'g_m_y_salvaboss_01',
	'g_m_y_salvagoon_01',
	'g_m_y_salvagoon_02',
	'g_m_y_salvagoon_03',
	'g_m_y_strpunk_01',
	'g_m_y_strpunk_02',
	'ig_abigail',
	'ig_ashley',
	'ig_bankman',
	'ig_barry',
	'ig_bestmen',
	'ig_beverly',
	'ig_car3guy1',
	'ig_car3guy2',
	'ig_chengsr',
	'ig_claypain',
	'ig_clay',
	'ig_cletus',
	'ig_dale',
	'ig_dreyfuss',
	'ig_hao',
	'ig_hunter',
	'ig_jewelass',
	'ig_jimmyboston',
	'ig_joeminuteman',
	'ig_josef',
	'ig_josh',
	'ig_kerrymcintosh',
	'ig_lifeinvad_01',
	'ig_lifeinvad_02',
	'ig_magenta',
	'ig_manuel',
	'ig_marnie',
	'ig_maryann',
	'ig_natalia',
	'ig_nigel',
	'ig_old_man1a',
	'ig_old_man2',
	'ig_oneil',
	'ig_paper',
	'ig_priest',
	'ig_ramp_gang',
	'ig_roccopelosi',
	's_f_y_bartender_01',
	's_f_y_hooker_01',
	's_f_y_hooker_02',
	's_f_y_hooker_03',
	's_f_y_shop_low',
	's_f_y_shop_mid',
	's_m_m_autoshop_01',
	's_m_m_autoshop_02',
	's_m_m_bouncer_01',
	's_m_m_hairdress_01',
	's_m_m_highsec_01',
	's_m_m_highsec_02',
	's_m_m_lifeinvad_01',
	's_m_m_mariachi_01',
	's_m_m_movprem_01',
	's_m_m_trucker_01',
	's_m_o_busker_01',
	's_m_y_barman_01',
	's_m_y_dealer_01',
	's_m_y_devinsec_01',
	's_m_y_robber_01',
	's_m_y_strvend_01',
	's_m_y_shop_mask',
	's_m_y_valet_01',
	's_m_y_winclean_01',
	's_m_y_xmech_01',
	's_m_y_xmech_02',
	'u_f_m_miranda',
	'u_f_y_bikerchic',
	'u_f_y_comjane',
	'u_f_y_hotposh_01',
	'u_f_y_jewelass_01',
	'u_f_y_mistress',
	'u_f_y_poppymich',
	'u_m_m_aldinapoli',
	'u_m_m_filmdirector',
	'u_m_m_griff_01',
	'u_m_m_jesus_01',
	'u_m_m_partytarget',
	'u_m_m_promourn_01',
	'u_m_m_rivalpap',
	'u_m_m_spyactor',
	'u_m_m_willyfist',
	'u_m_o_finguru_01',
	'u_m_o_taphillbilly',
	'u_m_o_tramp_01',
	'u_m_y_antonb',
	'u_m_y_cyclist_01',
	'u_m_y_fibmugger_01',
	'u_m_y_guido_01',
	'u_m_y_gunvend_01',
	'u_m_y_hippie_01',
	'u_m_y_mani',
	'u_m_y_militarybum',
	'u_m_y_paparazzi',
	'u_m_y_party_01',
	'u_m_y_proldriver_01',
	'u_m_y_sbike',
	'u_m_y_tattoo_01'
}