Config                      = {}
Config.Locale               = 'fr'

Config.Accounts             = { 'bank', 'black_money' }
Config.AccountLabels        = { bank = _U('bank'), black_money = _U('black_money') }

Config.EnableSocietyPayouts = true -- pagar o salario do jogador com dinheiro da sociedade? Requerimento: esx_society
Config.DisableWantedLevel   = true
Config.EnableHud            = false -- ativar o hud padrão? Exibir trabalho e contas atuais (dinheiro sujo, banco e dinheiro)

Config.PaycheckInterval     = 30 * 60000
Config.MaxPlayers           = GetConvarInt('sv_maxclients', 255) -- defina este valor para 255 se estiver executando o OneSync

Config.EnableDebug          = false

Config.Item = {
    {'coke', 'prop_coke_block_01'},
    {'weed', 'prop_weed_block_01'},

    {'acidesulfurique', 'bkr_prop_meth_hcacid'},
    {'antigel', 'bkr_prop_meth_sacid'},
    {'graineweed', 'hei_prop_heist_weed_block_01'},
    {'feuilledecoca', 'hei_prop_heist_weed_block_01'},
    {'cokebrut', 'prop_coke_block_01'},
    {'chanvre', 'hei_prop_heist_weed_block_01'},
    {'crystaldemeth', 'hei_prop_heist_weed_block_01'},
    {'meth_raw', 'hei_prop_heist_weed_block_01'},

    {'disc_ammo_pistol', 'prop_ld_ammo_pack_01'},
    {'disc_ammo_pistol_large', 'prop_ld_ammo_pack_01'},
    {'disc_ammo_shotgun', 'prop_ld_ammo_pack_02'},
    {'disc_ammo_smg', 'v_ret_gc_ammo4'},
    {'disc_ammo_rifle', 'prop_ld_ammo_pack_03'},
    {'disc_ammo_rifle_large', 'prop_ld_ammo_pack_03'},
    {'disc_ammo_snp', 'v_ret_gc_ammo1'},
    
    {'hei_prop_yah_table_01', 'hei_prop_yah_table_01'},
    {'hei_prop_yah_table_03', 'hei_prop_yah_table_03'},
    {'prop_chateau_table_01', 'prop_chateau_table_01'},
    {'prop_patio_lounger1_table', 'prop_patio_lounger1_table'},
    {'prop_proxy_chateau_table', 'prop_proxy_chateau_table'},
    {'prop_rub_table_02', 'prop_rub_table_02'},
    {'prop_rub_table_01', 'prop_rub_table_01'},
    {'prop_table_01', 'prop_table_01'},
    {'prop_table_02', 'prop_table_02'},
    {'prop_table_03', 'prop_table_03'},
    {'prop_table_04', 'prop_table_04'},
    {'prop_table_05', 'prop_table_05'},
    {'prop_table_06', 'prop_table_06'},
    {'prop_table_07', 'prop_table_07'},
    {'prop_table_08', 'prop_table_08'},
    {'prop_ven_market_table1', 'prop_ven_market_table1'},
    {'prop_yacht_table_01', 'prop_yacht_table_01'},
    {'prop_yacht_table_02', 'prop_yacht_table_02'},
    {'v_ret_fh_dinetable', 'v_ret_fh_dinetable'},
    {'v_ret_fh_dinetble', 'v_ret_fh_dinetble'},
    {'v_res_mconsoletrad', 'v_res_mconsoletrad'},
    {'prop_rub_table_02', 'prop_rub_table_02'},
    {'ba_prop_int_trad_table', 'ba_prop_int_trad_table'},
    {'xm_prop_x17_desk_cover_01a', 'xm_prop_x17_desk_cover_01a'},
    {'xm_prop_lab_desk_02', 'xm_prop_lab_desk_02'},
    {'xm_prop_lab_desk_01', 'xm_prop_lab_desk_01'},
    {'ex_mp_h_din_table_05', 'ex_mp_h_din_table_05'},
    {'hei_prop_yah_table_02', 'hei_prop_yah_table_02'},
    {'prop_ld_farm_table02', 'prop_ld_farm_table02'},
    {'prop_t_coffe_table', 'prop_t_coffe_table'},
    {'prop_t_coffe_table_02', 'prop_t_coffe_table_02'},

    {'prop_ld_greenscreen_01', 'prop_ld_greenscreen_01'},
    {'prop_tv_cam_02', 'prop_tv_cam_02'},

    {'p_pharm_unit_02', 'p_pharm_unit_02'},
    {'p_pharm_unit_01', 'p_pharm_unit_01'},
    {'p_v_43_safe_s', 'p_v_43_safe_s'},
    {'prop_bin_03a', 'prop_bin_03a'},
    {'prop_bin_07c', 'prop_bin_07c'},
    {'prop_bin_08open', 'prop_bin_08open'},
    {'prop_bin_10a', 'prop_bin_10a'},
    {'prop_devin_box_01', 'prop_devin_box_01'},
    {'prop_ld_int_safe_01', 'prop_ld_int_safe_01'},
    {'prop_dress_disp_01', 'prop_dress_disp_01'},
    {'prop_dress_disp_02', 'prop_dress_disp_02'},
    {'prop_dress_disp_03', 'prop_dress_disp_03'},
    {'prop_dress_disp_04', 'prop_dress_disp_04'},
    {'v_ret_fh_displayc', 'v_ret_fh_displayc'},

    {'apa_mp_h_bed_double_08', 'apa_mp_h_bed_double_08'},
    {'apa_mp_h_bed_double_09', 'apa_mp_h_bed_double_09'},
    {'apa_mp_h_bed_wide_05', 'apa_mp_h_bed_wide_05'},
    {'imp_prop_impexp_sofabed_01a', 'imp_prop_impexp_sofabed_01a'},
    {'apa_mp_h_bed_with_table_02', 'apa_mp_h_bed_with_table_02'},
    {'bka_prop_biker_campbed_01', 'bka_prop_biker_campbed_01'},
    {'apa_mp_h_yacht_bed_01', 'apa_mp_h_yacht_bed_01'},
    {'apa_mp_h_yacht_bed_02', 'apa_mp_h_yacht_bed_02'},
    {'p_lestersbed_s', 'p_lestersbed_s'},
    {'p_mbbed_s', 'p_mbbed_s'},
    {'v_res_d_bed', 'v_res_d_bed'},
    {'v_res_tre_bed2', 'v_res_tre_bed2'},
    {'v_res_tre_bed1', 'v_res_tre_bed1'},
    {'v_res_mdbed', 'v_res_mdbed'},
    {'v_res_msonbed', 'v_res_msonbed'},
    {'v_res_tt_bed', 'v_res_tt_bed'},

    {'prop_barrier_work05', 'prop_barrier_work05'},
    {'prop_boxpile_07d', 'prop_boxpile_07d'},
    {'p_ld_stinger_s', 'p_ld_stinger_s'},
    {'prop_roadcone02a', 'prop_roadcone02a'},

    {'hei_prop_yah_lounger', 'hei_prop_yah_lounger'},
    {'hei_prop_yah_seat_01', 'hei_prop_yah_seat_01'},
    {'hei_prop_yah_seat_02', 'hei_prop_yah_seat_02'},
    {'hei_prop_yah_seat_03', 'hei_prop_yah_seat_03'},
    {'miss_rub_couch_01', 'miss_rub_couch_01'},
    {'p_armchair_01_s', 'p_armchair_01_s'},
    {'p_ilev_p_easychair_s', 'p_ilev_p_easychair_s'},
    {'p_lev_sofa_s', 'p_lev_sofa_s'},
    {'p_patio_lounger1_s', 'p_patio_lounger1_s'},
    {'p_res_sofa_l_s', 'p_res_sofa_l_s'},
    {'p_v_med_p_sofa_s', 'p_v_med_p_sofa_s'},
    {'prop_bench_01a', 'prop_bench_01a'},
    {'prop_bench_06', 'prop_bench_06'},
    {'prop_ld_farm_chair01', 'prop_ld_farm_chair01'},
    {'prop_ld_farm_couch01', 'prop_ld_farm_couch01'},
    {'prop_ld_farm_couch02', 'prop_ld_farm_couch02'},
    {'prop_rub_couch04', 'prop_rub_couch04'},
    {'prop_t_sofa', 'prop_t_sofa'},
    {'prop_t_sofa_02', 'prop_t_sofa_02'},
    {'v_ilev_m_sofa', 'v_ilev_m_sofa'},
    {'v_res_tre_sofa_s', 'v_res_tre_sofa_s'},
    {'v_tre_sofa_mess_a_s', 'v_tre_sofa_mess_a_s'},
    {'v_tre_sofa_mess_b_s', 'v_tre_sofa_mess_b_s'},
    {'v_tre_sofa_mess_c_s', 'v_tre_sofa_mess_c_s'},

    {'prop_cs_trolley_01', 'prop_cs_trolley_01'},
    {'gr_prop_gr_tool_chest_01a', 'gr_prop_gr_tool_chest_01a'},
    {'gr_prop_gr_tool_draw_01a', 'gr_prop_gr_tool_draw_01a'},
    {'prop_carcreeper', 'prop_carcreeper'},
    {'prop_stockade_wheel_flat', 'prop_stockade_wheel_flat'},
    {'prop_toolchest_01', 'prop_toolchest_01'},
    {'prop_wheel_rim_02', 'prop_wheel_rim_02'},
    {'prop_wheel_tyre', 'prop_wheel_tyre'},
    {'prop_car_engine_01', 'prop_car_engine_01'},
    {'imp_prop_engine_hoist_02a', 'imp_prop_engine_hoist_02a'},
    {'prop_engine_hoist', 'prop_engine_hoist'},

    {'bkr_prop_duffel_bag_01a', 'bkr_prop_duffel_bag_01a'},
    {'v_med_emptybed', 'v_med_emptybed'},
    {'v_med_cor_emblmtable', 'v_med_cor_emblmtable'},
    {'v_ret_gc_bag01', 'v_ret_gc_bag01'},
    {'xm_prop_body_bag', 'xm_prop_body_bag'},

    {'prop_chair_01a', 'prop_chair_01a'},
    {'prop_chair_01b', 'prop_chair_01b'},
    {'prop_chair_02', 'prop_chair_02'},
    {'prop_chair_03', 'prop_chair_03'},
    {'prop_chair_04', 'prop_chair_04'},
    {'prop_chair_05', 'prop_chair_05'},
    {'prop_chair_06', 'prop_chair_06'},
    {'prop_chair_07', 'prop_chair_07'},
    {'prop_chair_08', 'prop_chair_08'},
    {'prop_chair_09', 'prop_chair_09'},
    {'prop_chair_10', 'prop_chair_10'},
    {'apa_mp_h_din_chair_04', 'apa_mp_h_din_chair_04'},
    {'apa_mp_h_din_chair_08', 'apa_mp_h_din_chair_08'},
    {'apa_mp_h_din_chair_09', 'apa_mp_h_din_chair_09'},
    {'apa_mp_h_din_chair_12', 'apa_mp_h_din_chair_12'},
    {'apa_mp_h_stn_chairarm_01', 'apa_mp_h_stn_chairarm_01'},
    {'apa_mp_h_stn_chairarm_02', 'apa_mp_h_stn_chairarm_02'},
    {'apa_mp_h_stn_chairarm_09', 'apa_mp_h_stn_chairarm_09'},
    {'apa_mp_h_stn_chairarm_11', 'apa_mp_h_stn_chairarm_11'},
    {'apa_mp_h_stn_chairarm_12', 'apa_mp_h_stn_chairarm_12'},
    {'apa_mp_h_stn_chairarm_13', 'apa_mp_h_stn_chairarm_13'},
    {'apa_mp_h_stn_chairarm_23', 'apa_mp_h_stn_chairarm_23'},
    {'apa_mp_h_stn_chairarm_24', 'apa_mp_h_stn_chairarm_24'},
    {'apa_mp_h_stn_chairarm_25', 'apa_mp_h_stn_chairarm_25'},
    {'apa_mp_h_stn_chairarm_26', 'apa_mp_h_stn_chairarm_26'},
    {'apa_mp_h_stn_chairstrip_08', 'apa_mp_h_stn_chairstrip_08'},
    {'apa_mp_h_stn_chairstrip_04', 'apa_mp_h_stn_chairstrip_04'},
    {'apa_mp_h_stn_chairstrip_05', 'apa_mp_h_stn_chairstrip_05'},
    {'apa_mp_h_stn_chairstrip_06', 'apa_mp_h_stn_chairstrip_06'},
    {'apa_mp_h_yacht_armchair_03', 'apa_mp_h_yacht_armchair_03'},
    {'apa_mp_h_yacht_armchair_04', 'apa_mp_h_yacht_armchair_04'},
    {'ba_prop_battle_club_chair_02', 'ba_prop_battle_club_chair_02'},
    {'apa_mp_h_yacht_strip_chair_01', 'apa_mp_h_yacht_strip_chair_01'},
    {'ba_prop_battle_club_chair_01', 'ba_prop_battle_club_chair_01'},
    {'ba_prop_battle_club_chair_03', 'ba_prop_battle_club_chair_03'},
    {'bka_prop_biker_boardchair01', 'bka_prop_biker_boardchair01'},
    {'bka_prop_biker_chairstrip_01', 'bka_prop_biker_chairstrip_01'},
    {'bka_prop_biker_chairstrip_02', 'bka_prop_biker_chairstrip_02'},
}